#ifndef _GRASS_FXH
#define _GRASS_FXH

// For translation of SHADERMODEL into __D3D9 etc.
#include "../../../../rage/base/src/grcore/config_switches.h"

// Size of each instance data (in vector4`s).
#define GRASS_INSTANCING_INSTANCE_SIZE	5

#define GRASS_INSTANCING_TRANSPORT_TEXTURE ((0 && (RSG_PC && __D3D11)) || (0 && RSG_DURANGO) || (0 && RSG_ORBIS))

#define GRASS_INSTANCING_TRANSPORT_CONSTANT_BUFFERS ((1 && (RSG_PC && __D3D11)) || (1 && RSG_DURANGO) || (1 && RSG_ORBIS))

#if GRASS_INSTANCING_TRANSPORT_TEXTURE && GRASS_INSTANCING_TRANSPORT_CONSTANT_BUFFERS
// Error! Can`t have both transport methods in use.
CompileTimeAssert(0);
#endif


#if GRASS_INSTANCING_TRANSPORT_TEXTURE
#define GRASS_INSTANCING_TEXTURE_WIDTH_IN_INSTANCES_POWER_OF_2	2
#define GRASS_INSTANCING_TEXTURE_HEIGHT_IN_INSTANCES			32
#define GRASS_INSTANCING_BUCKET_SIZE ((0x1<<GRASS_INSTANCING_TEXTURE_WIDTH_IN_INSTANCES_POWER_OF_2)*GRASS_INSTANCING_TEXTURE_HEIGHT_IN_INSTANCES)
#endif // GRASS_INSTANCING_TRANSPORT_TEXTURE

#if GRASS_INSTANCING_TRANSPORT_CONSTANT_BUFFERS

#if RSG_PC && __D3D9
// Deflated constant buffer size to keep the win32_30 version compiling.
//#define GRASS_INSTANCING_BUCKET_SIZE	1
#else
#define GRASS_INSTANCING_BUCKET_SIZE	256
#endif

#endif // GRASS_INSTANCING_TRANSPORT_CONSTANT_BUFFERS

#define GRASS_INSTANCING (GRASS_INSTANCING_TRANSPORT_TEXTURE || GRASS_INSTANCING_TRANSPORT_CONSTANT_BUFFERS)

#endif //_GRASS_FXH

