#ifndef __BUTTONENUM_H__
#define __BUTTONENUM_H__

enum PAD_BUTTON_NUMBER
{
	PAD_LEFTSTICKX = 0,
	PAD_LEFTSTICKY = 1,
	PAD_RIGHTSTICKX = 2,
	PAD_RIGHTSTICKY = 3,
	PAD_LEFTSHOULDER1 = 4,
	PAD_LEFTSHOULDER2 = 5,
	PAD_RIGHTSHOULDER1 = 6,
	PAD_RIGHTSHOULDER2 = 7,
	PAD_DPADUP = 8,
	PAD_DPADDOWN = 9,
	PAD_DPADLEFT = 10,
	PAD_DPADRIGHT = 11,
	PAD_START = 12,
	PAD_SELECT = 13,
	PAD_SQUARE = 14,
	PAD_TRIANGLE = 15,
	PAD_CROSS = 16,
	PAD_CIRCLE = 17,
	PAD_LEFTSHOCK = 18,
	PAD_RIGHTSHOCK = 19,
	PAD_R3 = 20,
	PAD_NO_BUTTON_PRESSED = 9999
};
#endif // __BUTTONENUM_H__

