//
// filename:	LiveCountryMappings.h
// description:	Intended only to be included by ProfileSettings.cpp
// to hold all mappings of LIVE country code constants to ISO codes
//

{XONLINE_COUNTRY_UNITED_ARAB_EMIRATES,              {'A', 'E'}},
{XONLINE_COUNTRY_ALBANIA,                           {'A', 'L'}},
{XONLINE_COUNTRY_ARMENIA,                           {'A', 'M'}},
{XONLINE_COUNTRY_ARGENTINA,                         {'A', 'R'}},
{XONLINE_COUNTRY_AUSTRIA,                           {'A', 'T'}},
{XONLINE_COUNTRY_AUSTRALIA,                         {'A', 'U'}},
{XONLINE_COUNTRY_AZERBAIJAN,                        {'A', 'Z'}},
{XONLINE_COUNTRY_BELGIUM,                           {'B', 'E'}},
{XONLINE_COUNTRY_BULGARIA,                          {'B', 'G'}},
{XONLINE_COUNTRY_BAHRAIN,                           {'B', 'H'}},
{XONLINE_COUNTRY_BRUNEI_DARUSSALAM,                 {'B', 'N'}},
{XONLINE_COUNTRY_BOLIVIA,                           {'B', 'O'}},
{XONLINE_COUNTRY_BRAZIL,                            {'B', 'R'}},
{XONLINE_COUNTRY_BELARUS,                           {'B', 'Y'}},
{XONLINE_COUNTRY_BELIZE,                            {'B', 'Z'}},
{XONLINE_COUNTRY_CANADA,                            {'C', 'A'}},
{XONLINE_COUNTRY_SWITZERLAND,                       {'C', 'H'}},
{XONLINE_COUNTRY_CHILE,                             {'C', 'L'}},
{XONLINE_COUNTRY_CHINA,                             {'C', 'N'}},
{XONLINE_COUNTRY_COLOMBIA,                          {'C', 'O'}},
{XONLINE_COUNTRY_COSTA_RICA,                        {'C', 'R'}},
{XONLINE_COUNTRY_CZECH_REPUBLIC,                    {'C', 'Z'}},
{XONLINE_COUNTRY_GERMANY,                           {'D', 'E'}},
{XONLINE_COUNTRY_DENMARK,                           {'D', 'K'}},
{XONLINE_COUNTRY_DOMINICAN_REPUBLIC,                {'D', 'O'}},
{XONLINE_COUNTRY_ALGERIA,                           {'D', 'Z'}},
{XONLINE_COUNTRY_ECUADOR,                           {'E', 'C'}},
{XONLINE_COUNTRY_ESTONIA,                           {'E', 'E'}},
{XONLINE_COUNTRY_EGYPT,                             {'E', 'G'}},
{XONLINE_COUNTRY_SPAIN,                             {'E', 'S'}},
{XONLINE_COUNTRY_FINLAND,                           {'F', 'I'}},
{XONLINE_COUNTRY_FAROE_ISLANDS,                     {'F', 'O'}},
{XONLINE_COUNTRY_FRANCE,                            {'F', 'R'}},
{XONLINE_COUNTRY_GREAT_BRITAIN,                     {'G', 'B'}},
{XONLINE_COUNTRY_GEORGIA,                           {'G', 'E'}},
{XONLINE_COUNTRY_GREECE,                            {'G', 'R'}},
{XONLINE_COUNTRY_GUATEMALA,                         {'G', 'T'}},
{XONLINE_COUNTRY_HONG_KONG,                         {'H', 'K'}},
{XONLINE_COUNTRY_HONDURAS,                          {'H', 'N'}},
{XONLINE_COUNTRY_CROATIA,                           {'H', 'R'}},
{XONLINE_COUNTRY_HUNGARY,                           {'H', 'U'}},
{XONLINE_COUNTRY_INDONESIA,                         {'I', 'D'}},
{XONLINE_COUNTRY_IRELAND,                           {'I', 'E'}},
{XONLINE_COUNTRY_ISRAEL,                            {'I', 'L'}},
{XONLINE_COUNTRY_INDIA,                             {'I', 'N'}},
{XONLINE_COUNTRY_IRAQ,                              {'I', 'Q'}}, //NOT IN SC
{XONLINE_COUNTRY_IRAN,                              {'I', 'R'}}, //NOT IN SC
{XONLINE_COUNTRY_ICELAND,                           {'I', 'S'}},
{XONLINE_COUNTRY_ITALY,                             {'I', 'T'}},
{XONLINE_COUNTRY_JAMAICA,                           {'J', 'M'}},
{XONLINE_COUNTRY_JORDAN,                            {'J', 'O'}},
{XONLINE_COUNTRY_JAPAN,                             {'J', 'P'}},
{XONLINE_COUNTRY_KENYA,                             {'K', 'E'}},
{XONLINE_COUNTRY_KYRGYZSTAN,                        {'K', 'G'}},
{XONLINE_COUNTRY_KOREA,                             {'K', 'R'}},
{XONLINE_COUNTRY_KUWAIT,                            {'K', 'W'}},
{XONLINE_COUNTRY_KAZAKHSTAN,                        {'K', 'Z'}},
{XONLINE_COUNTRY_LEBANON,                           {'L', 'B'}},
{XONLINE_COUNTRY_LIECHTENSTEIN,                     {'L', 'I'}},
{XONLINE_COUNTRY_LITHUANIA,                         {'L', 'T'}},
{XONLINE_COUNTRY_LUXEMBOURG,                        {'L', 'U'}},
{XONLINE_COUNTRY_LATVIA,                            {'L', 'V'}},
{XONLINE_COUNTRY_LIBYA,                             {'L', 'Y'}},
{XONLINE_COUNTRY_MOROCCO,                           {'M', 'A'}},
{XONLINE_COUNTRY_MONACO,                            {'M', 'C'}},
{XONLINE_COUNTRY_MACEDONIA,                         {'M', 'K'}},
{XONLINE_COUNTRY_MONGOLIA,                          {'M', 'N'}},
{XONLINE_COUNTRY_MACAU,                             {'M', 'O'}},
{XONLINE_COUNTRY_MALDIVES,                          {'M', 'V'}},
{XONLINE_COUNTRY_MEXICO,                            {'M', 'X'}},
{XONLINE_COUNTRY_MALAYSIA,                          {'M', 'Y'}},
{XONLINE_COUNTRY_NICARAGUA,                         {'N', 'I'}},
{XONLINE_COUNTRY_NETHERLANDS,                       {'N', 'L'}},
{XONLINE_COUNTRY_NORWAY,                            {'N', 'O'}},
{XONLINE_COUNTRY_NEW_ZEALAND,                       {'N', 'Z'}},
{XONLINE_COUNTRY_OMAN,                              {'O', 'M'}},
{XONLINE_COUNTRY_PANAMA,                            {'P', 'A'}},
{XONLINE_COUNTRY_PERU,                              {'P', 'E'}},
{XONLINE_COUNTRY_PHILIPPINES,                       {'P', 'H'}},
{XONLINE_COUNTRY_PAKISTAN,                          {'P', 'K'}},
{XONLINE_COUNTRY_POLAND,                            {'P', 'L'}},
{XONLINE_COUNTRY_PUERTO_RICO,                       {'P', 'R'}},
{XONLINE_COUNTRY_PORTUGAL,                          {'P', 'T'}},
{XONLINE_COUNTRY_PARAGUAY,                          {'P', 'Y'}},
{XONLINE_COUNTRY_QATAR,                             {'Q', 'A'}},
{XONLINE_COUNTRY_ROMANIA,                           {'R', 'O'}},
{XONLINE_COUNTRY_RUSSIAN_FEDERATION,                {'R', 'U'}},
{XONLINE_COUNTRY_SAUDI_ARABIA,                      {'S', 'A'}},
{XONLINE_COUNTRY_SWEDEN,                            {'S', 'E'}},
{XONLINE_COUNTRY_SINGAPORE,                         {'S', 'G'}},
{XONLINE_COUNTRY_SLOVENIA,                          {'S', 'I'}},
{XONLINE_COUNTRY_SLOVAK_REPUBLIC,                   {'S', 'K'}},
{XONLINE_COUNTRY_EL_SALVADOR,                       {'S', 'V'}},
{XONLINE_COUNTRY_SYRIA,                             {'S', 'Y'}},
{XONLINE_COUNTRY_THAILAND,                          {'T', 'H'}},
{XONLINE_COUNTRY_TUNISIA,                           {'T', 'N'}},
{XONLINE_COUNTRY_TURKEY,                            {'T', 'R'}},
{XONLINE_COUNTRY_TRINIDAD_AND_TOBAGO,               {'T', 'T'}},
{XONLINE_COUNTRY_TAIWAN,                            {'T', 'W'}},
{XONLINE_COUNTRY_UKRAINE,                           {'U', 'A'}},
{XONLINE_COUNTRY_UNITED_STATES,                     {'U', 'S'}},
{XONLINE_COUNTRY_URUGUAY,                           {'U', 'Y'}},
{XONLINE_COUNTRY_UZBEKISTAN,                        {'U', 'Z'}},
{XONLINE_COUNTRY_VENEZUELA,                         {'V', 'E'}},
{XONLINE_COUNTRY_VIET_NAM,                          {'V', 'N'}},
{XONLINE_COUNTRY_YEMEN,                             {'Y', 'E'}},
{XONLINE_COUNTRY_SOUTH_AFRICA,                      {'Z', 'A'}},
{XONLINE_COUNTRY_ZIMBABWE,                          {'Z', 'W'}}, //NOT IN SC
{XONLINE_COUNTRY_AFGHANISTAN,                       {'A', 'F'}},
{XONLINE_COUNTRY_ANDORA,                            {'A', 'D'}},
{XONLINE_COUNTRY_ANGOLA,                            {'A', 'O'}},
{XONLINE_COUNTRY_ANGUILLA,                          {'A', 'I'}},
{XONLINE_COUNTRY_ANTIGUA_BARBUDA,                   {'A', 'G'}},
{XONLINE_COUNTRY_ARUBA,                             {'A', 'W'}},
{XONLINE_COUNTRY_BAHAMAS,                           {'B', 'S'}},
{XONLINE_COUNTRY_BANGLADESH,                        {'B', 'D'}},
{XONLINE_COUNTRY_BARBADOS,                          {'B', 'B'}},
{XONLINE_COUNTRY_BENIN,                             {'B', 'J'}},
{XONLINE_COUNTRY_BERMUDA,                           {'B', 'M'}},
{XONLINE_COUNTRY_BHUTAN,                            {'B', 'T'}},
{XONLINE_COUNTRY_BOSNIA_HERZEGOVINA,                {'B', 'A'}},
{XONLINE_COUNTRY_BOTSWANA,                          {'B', 'W'}},
{XONLINE_COUNTRY_BURKINA_FASO,                      {'B', 'F'}},
{XONLINE_COUNTRY_BURUNDI,                           {'B', 'I'}},
{XONLINE_COUNTRY_CAMBODIA,                          {'K', 'H'}},
{XONLINE_COUNTRY_CAMEROON,                          {'C', 'M'}},
{XONLINE_COUNTRY_CAPE_VERDE,                        {'C', 'V'}},
{XONLINE_COUNTRY_CAYMAN_ISLANDS,                    {'K', 'Y'}},
{XONLINE_COUNTRY_CENTRAL_AFRICAN_REPUBLIC,          {'C', 'F'}},
{XONLINE_COUNTRY_CHAD,                              {'T', 'D'}},
{XONLINE_COUNTRY_CHRISTMAS_ISLAND,                  {'C', 'X'}},
{XONLINE_COUNTRY_COCOS_KEELING_ISLANDS,             {'C', 'C'}},
{XONLINE_COUNTRY_COMOROS,                           {'K', 'M'}},
{XONLINE_COUNTRY_CONGO,                             {'C', 'G'}}, //NOT IN SC
{XONLINE_COUNTRY_CONGO_DEMOCRATIC_REPUBLIC,         {'C', 'D'}}, //NOT IN SC
{XONLINE_COUNTRY_COOK_ISLANDS,                      {'C', 'K'}},
{XONLINE_COUNTRY_COTE_DLVOIRE,                      {'C', 'I'}}, //NOT IN SC
{XONLINE_COUNTRY_CYPRUS,                            {'C', 'Y'}},
{XONLINE_COUNTRY_DJIBOUTI,                          {'D', 'J'}},
{XONLINE_COUNTRY_DOMINICA,                          {'D', 'M'}},
{XONLINE_COUNTRY_EQUATORIAL_GUINEA,                 {'G', 'Q'}},
{XONLINE_COUNTRY_ERITREA,                           {'E', 'R'}},
{XONLINE_COUNTRY_ETHIOPIA,                          {'E', 'T'}},
{XONLINE_COUNTRY_FALKLAND_ISLANDS_MALVINAS,         {'F', 'K'}},
{XONLINE_COUNTRY_FIJI,                              {'F', 'J'}},
{XONLINE_COUNTRY_FRENCH_GUIANA,                     {'G', 'F'}},
{XONLINE_COUNTRY_FRENCH_POLYNESIA,                  {'P', 'F'}},
{XONLINE_COUNTRY_GABON,                             {'G', 'A'}},
{XONLINE_COUNTRY_GAMBIA,                            {'G', 'M'}},
{XONLINE_COUNTRY_GHANA,                             {'G', 'H'}},
{XONLINE_COUNTRY_GIBRALTAR,                         {'G', 'I'}},
{XONLINE_COUNTRY_GREENLAND,                         {'G', 'L'}},
{XONLINE_COUNTRY_GRENADA,                           {'G', 'D'}},
{XONLINE_COUNTRY_GUADELOUPE,                        {'G', 'P'}},
{XONLINE_COUNTRY_GUERNSEY,                          {'G', 'G'}}, //NOT IN SC
{XONLINE_COUNTRY_GUINEA,                            {'G', 'N'}},
{XONLINE_COUNTRY_GUINEA_BISSAU,                     {'G', 'W'}},
{XONLINE_COUNTRY_GUYANA,                            {'G', 'Y'}},
{XONLINE_COUNTRY_HAITI,                             {'H', 'T'}},
{XONLINE_COUNTRY_JERSEY,                            {'J', 'E'}}, //NOT IN SC
{XONLINE_COUNTRY_KIRIBATI,                          {'K', 'I'}},
{XONLINE_COUNTRY_LAOS_PEOPLES_DEMOCRATIC_REPUBLIC,  {'L', 'A'}},
{XONLINE_COUNTRY_LESOTHO,                           {'L', 'S'}},
{XONLINE_COUNTRY_LIBERIA,                           {'L', 'R'}}, //NOT IN SC
{XONLINE_COUNTRY_MADAGASCAR,                        {'M', 'G'}},
{XONLINE_COUNTRY_MALAWI,                            {'M', 'W'}},
{XONLINE_COUNTRY_MALI,                              {'M', 'L'}},
{XONLINE_COUNTRY_MALTA,                             {'M', 'T'}},
{XONLINE_COUNTRY_MARSHALL_ISLANDS,                  {'M', 'H'}},
{XONLINE_COUNTRY_MARTINIQUE,                        {'M', 'Q'}},
{XONLINE_COUNTRY_MAURITANIA,                        {'M', 'R'}},
{XONLINE_COUNTRY_MAURITIUS,                         {'M', 'U'}},
{XONLINE_COUNTRY_MAYOTTE,                           {'Y', 'T'}},
{XONLINE_COUNTRY_MICRONESIA,                        {'F', 'M'}},
{XONLINE_COUNTRY_MOLDOVA,                           {'M', 'D'}},
{XONLINE_COUNTRY_MONTENEGRO,                        {'M', 'E'}}, //NOT IN SC, now Serbia and Montenegro
{XONLINE_COUNTRY_MONTSERRAT,                        {'M', 'S'}},
{XONLINE_COUNTRY_MOZAMBIQUE,                        {'M', 'Z'}},
{XONLINE_COUNTRY_MYANMAR,                           {'M', 'M'}}, //NOT IN SC (was Burma)
{XONLINE_COUNTRY_NAMIBIA,                           {'N', 'A'}},
{XONLINE_COUNTRY_NAURU,                             {'N', 'R'}},
{XONLINE_COUNTRY_NEPAL,                             {'N', 'P'}},
{XONLINE_COUNTRY_NETHERLANDS_ANTILLES,              {'A', 'N'}},
{XONLINE_COUNTRY_NEW_CALEDONIA,                     {'N', 'C'}},
{XONLINE_COUNTRY_NIGER,                             {'N', 'E'}},
{XONLINE_COUNTRY_NIGERIA,                           {'N', 'G'}},
{XONLINE_COUNTRY_NIUE,                              {'N', 'U'}},
{XONLINE_COUNTRY_NORFOLK_ISLAND,                    {'N', 'F'}},
{XONLINE_COUNTRY_PALAU,                             {'P', 'W'}},
{XONLINE_COUNTRY_PALESTINIAN_TERRITORY,             {'P', 'S'}}, //NOT IN SC
{XONLINE_COUNTRY_PAPUA_NEW_GUINEA,                  {'P', 'G'}},
{XONLINE_COUNTRY_PITCAIRN,                          {'P', 'N'}},
{XONLINE_COUNTRY_REUNION,                           {'R', 'E'}},
{XONLINE_COUNTRY_RWANDA,                            {'R', 'W'}}, //NOT IN SC
{XONLINE_COUNTRY_SAMOA,                             {'W', 'S'}}, //NOT IN SC (as WS, present as EH)
{XONLINE_COUNTRY_SAN_MARINO,                        {'S', 'M'}},
{XONLINE_COUNTRY_SAO_TOME_AND_PRINCIPE,             {'S', 'T'}},
{XONLINE_COUNTRY_SENEGAL,                           {'S', 'N'}},
{XONLINE_COUNTRY_SERBIA,                            {'R', 'S'}}, //Now Serbia and Montenegro
{XONLINE_COUNTRY_SEYCHELLES,                        {'S', 'C'}},
{XONLINE_COUNTRY_SIERRA_LEONE,                      {'S', 'L'}}, //NOT IN SC
{XONLINE_COUNTRY_SOLOMON_ISLANDS,                   {'S', 'B'}},
{XONLINE_COUNTRY_SOMALIA,                           {'S', 'O'}}, //NOT IN SC
{XONLINE_COUNTRY_SRI_LANKA,                         {'L', 'K'}},
{XONLINE_COUNTRY_SAINT_HELENA_AND_TRISTAN_DA_CUNHA, {'S', 'H'}},
{XONLINE_COUNTRY_SAINT_KITTS_AND_NEVIS,             {'K', 'N'}},
{XONLINE_COUNTRY_SAINT_LUCIA,                       {'L', 'C'}},
{XONLINE_COUNTRY_SAINT_PIERRE_AND_MIQUELON,         {'P', 'M'}},
{XONLINE_COUNTRY_SAINT_VINCENT_AND_THE_GRENADINES,  {'V', 'C'}},
{XONLINE_COUNTRY_SURINAME,                          {'S', 'R'}},
{XONLINE_COUNTRY_SWAZILAND,                         {'S', 'Z'}},
{XONLINE_COUNTRY_TAJIKISTAN,                        {'T', 'J'}},
{XONLINE_COUNTRY_TANZANIA,                          {'T', 'Z'}},
{XONLINE_COUNTRY_TIMOR_LESTE,                       {'T', 'L'}}, //NOT IN SC
{XONLINE_COUNTRY_TOGO,                              {'T', 'G'}},
{XONLINE_COUNTRY_TOKELAU,                           {'T', 'K'}},
{XONLINE_COUNTRY_TONGA,                             {'T', 'O'}},
{XONLINE_COUNTRY_TURKMENISTAN,                      {'T', 'M'}},
{XONLINE_COUNTRY_TURKS_AND_CAICOS_ISLANDS,          {'T', 'C'}},
{XONLINE_COUNTRY_TUVALU,                            {'T', 'V'}},
{XONLINE_COUNTRY_UGANDA,                            {'U', 'G'}},
{XONLINE_COUNTRY_VANUATU,                           {'V', 'U'}},
{XONLINE_COUNTRY_VATICAN_CITY,                      {'V', 'A'}},
{XONLINE_COUNTRY_VIRGIN_ISLANDS_BRITISH,            {'V', 'G'}},
{XONLINE_COUNTRY_WALLIS_AND_FUTUNA,                 {'W', 'F'}},
{XONLINE_COUNTRY_WESTERN_SAHARA,                    {'E', 'H'}}, //IN SC AS Samoa
{XONLINE_COUNTRY_ZAMBIA,                            {'Z', 'M'}}