/////////////////////////////////////////////////////////////////////////////////
//
// FILE    : MultiplayerGamerTagList.h
// PURPOSE : manages the list of multiplayer gamer tag icons
// AUTHOR  : James Chagaris
// STARTED : 2/26/2013
//
/////////////////////////////////////////////////////////////////////////////////

#ifndef __MULTIPLAYER_GAMER_TAG_LIST_H__
#define __MULTIPLAYER_GAMER_TAG_LIST_H__

enum eTAG_FLAGS
{
	TF_NONE = 0,
	TF_SHOULD_EXIST = BIT(0),
	TF_LEFT_ROW = BIT(1),
	TF_CENTER_ROW = BIT(2),
	TF_BASE_LEVEL = BIT(3),
	TF_LOCATION_MASK = TF_LEFT_ROW | TF_CENTER_ROW | TF_BASE_LEVEL
};

#define GAMER_TAG_LIST \
	GAMER_TAG_OBJ(MP_TAG_GAMER_NAME,				GAMER_NAME,				TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_CREW_TAG,					CREW_TAG,				TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_HEALTH_BAR,				healthArmour,			TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_BIG_TEXT,					BIG_TEXT,				TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_AUDIO,						AUDIO_ICON,				TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_USING_MENU,				MP_USING_MENU,			TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_PASSIVE_MODE,				MP_PASSIVE_MODE,		TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_WANTED_LEVEL,				WANTED_STARS,			TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_DRIVER,					MP_DRIVER,				TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_CO_DRIVER,					MP_CO_DRIVER,			TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_TAGGED,					MP_TAGGED,				TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_GAMER_NAME_NEARBY,			GAMER_NAME_NEARBY,		TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_ARROW,						ARROW,					TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_PACKAGES,					MP_PACKAGES,			TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_IF_PED_FOLLOWING,			INV_IF_PED_FOLLOWING,	TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_RANK,						RANK_TEXT,				TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_TYPING,					MP_TYPING,				TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_PACKAGE_LARGE,				MP_BAG_LARGE,			TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_TRACKIFY,					MP_TAG_ARROW,			TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_GANG_CEO,					MP_GANG_CEO,			TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_GANG_BIKER,				MP_GANG_BIKER,			TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_BIKER_ARROW,				BIKER_ARROW,			TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_MC_ROLE_PRESIDENT,			MC_ROLE_PRESIDENT,		TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_MC_ROLE_VICE_PRESIDENT,	MC_ROLE_VICE_PRESIDENT,	TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_MC_ROLE_ROAD_CAPTAIN,		MC_ROLE_ROAD_CAPTAIN,	TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_MC_ROLE_SARGEANT,			MC_ROLE_SARGEANT,		TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_MC_ROLE_ENFORCER,			MC_ROLE_ENFORCER,		TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_MC_ROLE_PROSPECT,			MC_ROLE_PROSPECT,		TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_TRANSMITTER,				MP_TRANSMITTER,			TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_BOMB,						MP_BOMB,				TF_SHOULD_EXIST)
#if ARCHIVED_SUMMER_CONTENT_ENABLED 
\
	GAMER_TAG_OBJ(MP_TAG_ARREST,					MP_ARREST,				TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_CNC_DOT,					CNC_DOT,				TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_CNC_VAN,					CNC_VAN,				TF_SHOULD_EXIST) \
	GAMER_TAG_OBJ(MP_TAG_CNC_THREAT,				CNC_THREAT,				TF_SHOULD_EXIST)
#endif

enum eMP_TAG
{
#define GAMER_TAG_OBJ(val, asName, defaultTags) val,
	GAMER_TAG_LIST
#undef GAMER_TAG_OBJ
	MAX_MP_TAGS
};


#endif
// eof
