//
// filename:	optimisations.h
// description:	
//

#ifndef INC_OPTIMISATIONS_H_
#define INC_OPTIMISATIONS_H_

// --- Defines ------------------------------------------------------------------

#define AI_OPTIMISATIONS_OFF						0
#define AI_COVER_OPTIMISATIONS_OFF					0
#define AI_EVENT_OPTIMISATIONS_OFF					0
#define AI_NAVIGATION_OPTIMSATIONS_OFF				0
#define AI_SCENARIO_OPTIMSATIONS_OFF				0
#define AI_VEHICLE_OPTIMISATIONS_OFF				0
#define AI_MOTION_OPTIMISATIONS_OFF					0
#define AI_MOVEMENT_OPTIMISATIONS_OFF				0
#define AI_WEAPON_OPTIMISATIONS_OFF					0
#define ANIM_OPTIMISATIONS_OFF						0
#define AUDIO_OPTIMISATIONS_OFF						0
#define AUDIO_AMBIENCE_OPTIMISATIONS_OFF			0
#define AUDIO_ENVIRONMENT_OPTIMISATIONS_OFF			0
#define AUDIO_MUSIC_OPTIMISATIONS_OFF				0
#define AUDIO_VEHICLES_OPTIMISATIONS_OFF			0
#define AUDIO_DYNAMICMIXING_OPTIMISATIONS_OFF		0
#define AUDIO_PEDS_OPTIMISATIONS_OFF				0
#define AUDIO_WEAPONS_OPTIMISATIONS_OFF				0
#define CAMERA_OPTIMISATIONS_OFF					0
#define CLOTH_OPTIMISATIONS_OFF						0
#define ENTITY_OPTIMISATIONS_OFF					0
#define FRONTEND_OPTIMISATIONS_OFF					0
#define FRONTEND_MENU_OPTIMISATIONS_OFF				0
#define FRONTEND_STORE_OPTIMISATIONS_OFF			0
#define FRONTEND_SCRIPT_OPTIMISATIONS_OFF			0
#define FRONTEND_STATS_OPTIMISATIONS_OFF			0
#define FRONTEND_NETWORK_OPTIMISATIONS_OFF			0
#define NETWORK_OPTIMISATIONS_OFF					0
#define NETWORK_SHOP_OPTIMISATIONS_OFF			    0
#define NETWORK_OBJECT_OPTIMISATIONS_OFF			0
#define PED_OPTIMISATIONS_OFF						0
#define PHYSICS_OPTIMISATIONS_OFF					0
#define RENDER_OPTIMISATIONS_OFF					0
#define REPLAY_OPTIMISATIONS_OFF					0
#define REPLAY_COORDINATOR_OPTIMISATIONS_OFF		0
#define SCENE_OPTIMISATIONS_OFF						0
#define SCRIPT_OPTIMISATIONS_OFF					0
#define VEHICLE_OPTIMISATIONS_OFF					0
#define VFX_PTFX_OPTIMISATIONS_OFF					0
#define VFX_DECAL_OPTIMISATIONS_OFF					0
#define VFX_SYSTEM_OPTIMISATIONS_OFF				0
#define VFX_MISC_OPTIMISATIONS_OFF					0
#define WEAPON_OPTIMISATIONS_OFF					0
#define TEXT_OPTIMISATIONS_OFF						0
#define SCALEFORM_OPTIMISATIONS_OFF					0
#define SAVEGAME_OPTIMISATIONS_OFF  				0

#if AI_OPTIMISATIONS_OFF
#define AI_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define AI_OPTIMISATIONS()
#endif	//AI_OPTIMISATIONS_OFF

#if AI_OPTIMISATIONS_OFF
#define AI_OPTIMISATIONS_OFF_ONLY(x)	x
#else
#define AI_OPTIMISATIONS_OFF_ONLY(x)
#endif	//AI_OPTIMISATIONS_OFF

#if AI_COVER_OPTIMISATIONS_OFF
#define AI_COVER_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define AI_COVER_OPTIMISATIONS()
#endif	//AI_COVER_OPTIMISATIONS_OFF

#if AI_EVENT_OPTIMISATIONS_OFF
#define AI_EVENT_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define AI_EVENT_OPTIMISATIONS()
#endif	//AI_OPTIMISATIONS_OFF

#if AI_NAVIGATION_OPTIMSATIONS_OFF
#define AI_NAVIGATION_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define AI_NAVIGATION_OPTIMISATIONS()
#endif	//AI_OPTIMISATIONS_OFF

#if AI_SCENARIO_OPTIMSATIONS_OFF
#define AI_SCENARIO_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define AI_SCENARIO_OPTIMISATIONS()
#endif	//AI_OPTIMISATIONS_OFF

#if AI_VEHICLE_OPTIMISATIONS_OFF
#define AI_VEHICLE_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define AI_VEHICLE_OPTIMISATIONS()
#endif	//AI_VEHICLE_OPTIMISATIONS_OFF

#if AI_MOTION_OPTIMISATIONS_OFF
#define AI_MOTION_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define AI_MOTION_OPTIMISATIONS()
#endif	//AI_MOTION_OPTIMISATIONS_OFF

#if AI_MOVEMENT_OPTIMISATIONS_OFF
#define AI_MOVEMENT_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define AI_MOVEMENT_OPTIMISATIONS()
#endif	//AI_MOVEMENT_OPTIMISATIONS_OFF

#if AI_WEAPON_OPTIMISATIONS_OFF
#define AI_WEAPON_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define AI_WEAPON_OPTIMISATIONS()
#endif	//AI_WEAPON_OPTIMISATIONS_OFF

#if ANIM_OPTIMISATIONS_OFF
#define ANIM_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define ANIM_OPTIMISATIONS()
#endif	//ANIM_OPTIMISATIONS_OFF

#if AUDIO_OPTIMISATIONS_OFF
#define AUDIO_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define AUDIO_OPTIMISATIONS()
#endif	//AUDIO_OPTIMISATIONS_OFF

#if AUDIO_AMBIENCE_OPTIMISATIONS_OFF
#define AUDIO_AMBIENCE_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define AUDIO_AMBIENCE_OPTIMISATIONS()
#endif	//AUDIO_AMBIENCE_OPTIMISATIONS

#if AUDIO_ENVIRONMENT_OPTIMISATIONS_OFF
#define AUDIO_ENVIRONMENT_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define AUDIO_ENVIRONMENT_OPTIMISATIONS()
#endif	//AUDIO_ENVIRONMENT_OPTIMISATIONS

#if AUDIO_MUSIC_OPTIMISATIONS_OFF
#define AUDIO_MUSIC_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define AUDIO_MUSIC_OPTIMISATIONS()
#endif	//AUDIO_MUSIC_OPTIMISATIONS

#if AUDIO_VEHICLES_OPTIMISATIONS_OFF
#define AUDIO_VEHICLES_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define AUDIO_VEHICLES_OPTIMISATIONS()
#endif	//AUDIO_VEHICLES_OPTIMISATIONS

#if AUDIO_DYNAMICMIXING_OPTIMISATIONS_OFF
#define AUDIO_DYNAMICMIXING_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define AUDIO_DYNAMICMIXING_OPTIMISATIONS()
#endif	//AUDIO_DYNAMICMIXING_OPTIMISATIONS

#if AUDIO_PEDS_OPTIMISATIONS_OFF
#define AUDIO_PEDS_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define AUDIO_PEDS_OPTIMISATIONS()
#endif	//AUDIO_DYNAMICMIXING_OPTIMISATIONS

#if AUDIO_WEAPONS_OPTIMISATIONS_OFF
#define AUDIO_WEAPONS_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define AUDIO_WEAPONS_OPTIMISATIONS()
#endif	//AUDIO_DYNAMICMIXING_OPTIMISATIONS

#if CAMERA_OPTIMISATIONS_OFF
#define CAMERA_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define CAMERA_OPTIMISATIONS()
#endif	//CAMERA_OPTIMISATIONS_OFF

#if CLOTH_OPTIMISATIONS_OFF
#define CLOTH_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define CLOTH_OPTIMISATIONS()
#endif	//CLOTH_OPTIMISATIONS_OFF

#if ENTITY_OPTIMISATIONS_OFF
#define ENTITY_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define ENTITY_OPTIMISATIONS()
#endif	//ENTITY_OPTIMISATIONS_OFF

#if FRONTEND_OPTIMISATIONS_OFF
#define FRONTEND_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define FRONTEND_OPTIMISATIONS()
#endif	//FRONTEND_OPTIMISATIONS_OFF

#if FRONTEND_STORE_OPTIMISATIONS_OFF
#define FRONTEND_STORE_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define FRONTEND_STORE_OPTIMISATIONS()
#endif	//FRONTEND_STORE_OPTIMISATIONS_OFF

#if FRONTEND_SCRIPT_OPTIMISATIONS_OFF
#define FRONTEND_SCRIPT_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define FRONTEND_SCRIPT_OPTIMISATIONS()
#endif	//FRONTEND_SCRIPT_OPTIMISATIONS_OFF

#if FRONTEND_STATS_OPTIMISATIONS_OFF
#define FRONTEND_STATS_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define FRONTEND_STATS_OPTIMISATIONS()
#endif	//FRONTEND_STATS_OPTIMISATIONS_OFF


#if FRONTEND_MENU_OPTIMISATIONS_OFF
#define FRONTEND_MENU_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define FRONTEND_MENU_OPTIMISATIONS()
#endif	//FRONTEND_STATS_OPTIMISATIONS_OFF


#if FRONTEND_NETWORK_OPTIMISATIONS_OFF
#define FRONTEND_NETWORK_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define FRONTEND_NETWORK_OPTIMISATIONS()
#endif	//FRONTEND_STATS_OPTIMISATIONS_OFF


#if NETWORK_OPTIMISATIONS_OFF
#define NETWORK_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define NETWORK_OPTIMISATIONS()
#endif	//NETWORK_OPTIMISATIONS_OFF

#if NETWORK_SHOP_OPTIMISATIONS_OFF
#define NETWORK_SHOP_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define NETWORK_SHOP_OPTIMISATIONS()
#endif	//NETWORK_SHOP_OPTIMISATIONS_OFF

#if NETWORK_OBJECT_OPTIMISATIONS_OFF
#define NETWORK_OBJECT_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define NETWORK_OBJECT_OPTIMISATIONS()
#endif	//NETWORK_OBJECT_OPTIMISATIONS_OFF

#if PED_OPTIMISATIONS_OFF
#define PED_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define PED_OPTIMISATIONS()
#endif	//PED_OPTIMISATIONS_OFF

#if PHYSICS_OPTIMISATIONS_OFF
#define PHYSICS_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define PHYSICS_OPTIMISATIONS()
#endif	//PHYSICS_OPTIMISATIONS_OFF

#if RENDER_OPTIMISATIONS_OFF
#define RENDER_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define RENDER_OPTIMISATIONS()
#endif	//RENDER_OPTIMISATIONS_OFF

#if REPLAY_OPTIMISATIONS_OFF
#define REPLAY_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define REPLAY_OPTIMISATIONS()
#endif	//REPLAY_OPTIMISATIONS_OFF

#if REPLAY_COORDINATOR_OPTIMISATIONS_OFF
#define REPLAY_COORDINATOR_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define REPLAY_COORDINATOR_OPTIMISATIONS()
#endif	//REPLAY_COORDINATOR_OPTIMISATIONS_OFF

#if SCENE_OPTIMISATIONS_OFF
#define SCENE_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define SCENE_OPTIMISATIONS()
#endif	//SCENE_OPTIMISATIONS_OFF

#if SCRIPT_OPTIMISATIONS_OFF
#define SCRIPT_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define SCRIPT_OPTIMISATIONS()
#endif	//SCRIPT_OPTIMISATIONS_OFF

#if VEHICLE_OPTIMISATIONS_OFF
#define VEHICLE_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define VEHICLE_OPTIMISATIONS()
#endif	//VEHICLE_OPTIMISATIONS_OFF

#if VFX_PTFX_OPTIMISATIONS_OFF
#define VFX_PTFX_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define VFX_PTFX_OPTIMISATIONS()
#endif	//VFX_PTFX_OPTIMISATIONS_OFF

#if VFX_DECAL_OPTIMISATIONS_OFF
#define VFX_DECAL_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define VFX_DECAL_OPTIMISATIONS()
#endif	//VFX_DECAL_OPTIMISATIONS_OFF

#if VFX_SYSTEM_OPTIMISATIONS_OFF
#define VFX_SYSTEM_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define VFX_SYSTEM_OPTIMISATIONS()
#endif	//VFX_SYSTEM_OPTIMISATIONS_OFF

#if VFX_MISC_OPTIMISATIONS_OFF
#define VFX_MISC_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define VFX_MISC_OPTIMISATIONS()
#endif	//VFX_MISC_OPTIMISATIONS_OFF

#if WEAPON_OPTIMISATIONS_OFF
#define WEAPON_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define WEAPON_OPTIMISATIONS()
#endif	//WEAPON_OPTIMISATIONS_OFF

#if TEXT_OPTIMISATIONS_OFF
#define TEXT_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define TEXT_OPTIMISATIONS()
#endif	//TEXT_OPTIMISATIONS_OFF

#if SCALEFORM_OPTIMISATIONS_OFF
#define SCALEFORM_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define SCALEFORM_OPTIMISATIONS()
#endif	//SCALEFORM_OPTIMISATIONS_OFF

#if SAVEGAME_OPTIMISATIONS_OFF
#define SAVEGAME_OPTIMISATIONS()	OPTIMISATIONS_OFF()
#else
#define SAVEGAME_OPTIMISATIONS()
#endif	//SAVEGAME_OPTIMISATIONS_OFF

#endif // !INC_OPTIMISATIONS_H_
