

#include "../../../rage/base/src/grcore/config_switches.h"

#define TERRAIN_OPEN_EDGE_INFO_COMMON_FLOOR -2000.0f

// Platforms.
#define TERRAIN_TESSELLATION_PLATFORMS	((0 && (RSG_PC && __D3D11)) || (0 && RSG_DURANGO) || (0 && RSG_ORBIS))
// C++ side guard.
#define TERRAIN_TESSELLATION_SUPPORT (TERRAIN_TESSELLATION_PLATFORMS && RAGE_SUPPORT_TESSELLATION_TECHNIQUES)

// Shader guards.
#ifdef __SHADERMODEL

#define TERRAIN_TESSELLATION_SHADER_CODE (TERRAIN_TESSELLATION_SUPPORT && defined(USE_TERRAIN_TESSELLATION))
#define TERRAIN_TESSELLATION_SHADER_DATA ((TERRAIN_TESSELLATION_SUPPORT || ((__SHADERMODEL == 30) && __WIN32PC)) && defined(USE_TERRAIN_TESSELLATION))

#if TERRAIN_TESSELLATION_SHADER_CODE
	#define TERRAIN_TESSELLATION_SHADER_CODE_ONLY(x) x
#else
	#define TERRAIN_TESSELLATION_SHADER_CODE_ONLY(x)	
#endif

#endif

 

