#ifndef GLASSPANEINFO_H_
#define GLASSPANEINFO_H_

#define GLASS_PANE_SYNCING_ACTIVE		0

#if GLASS_PANE_SYNCING_ACTIVE
	#define GLASS_PARAM(X) X
#else
	#define GLASS_PARAM(X) UNUSED_PARAM(X)
#endif /* GLASS_PANE_SYNCING_ACTIVE */

#endif /* GLASSPANEINFO_H_ */