#ifndef INC_EVENT_PRIORITIES_H
#define INC_EVENT_PRIORITIES_H

//////////////////////////////////////////////////////////////////////////
// Set all event priorities in the same place
// so we can order and compare them
//////////////////////////////////////////////////////////////////////////

enum eEventPriorityList
{
	// Totally random ambient stuff
	E_PRIORITY_RIDE_TRAIN,
	E_PRIORITY_PED_TO_CHASE,
	E_PRIORITY_PED_TO_FLEE,
	E_PRIORITY_VEHICLE_TO_STEAL,
	E_PRIORITY_SHOVE_PED,
	E_PRIORITY_OPEN_DOOR,
	// Investigate events
	E_PRIORITY_COMMUNICATE_EVENT,
	E_PRIORITY_SOUND_DYNAMIC,
	E_PRIORITY_FIRE_NEARBY,
	E_PRIORITY_PED_ON_CAR_ROOF,
	// React to seeing other peds
	E_PRIORITY_RAN_OVER_PED,
	// Lower priority shocking events, mostly those that affect others
	E_PRIORITY_SHOCKING_EVENT_INTERESTING,				// Note: we may want to move these around relative to other events, they don't all have to be together.
	E_PRIORITY_SHOCKING_EVENT_AFFECTS_OTHERS,
	// Event reactions
	E_PRIORITY_PED_DEAD,
	E_PRIORITY_SEEN_COP,
	E_PRIORITY_REACTION_COMBAT_VICTORY,
	E_PRIORITY_FOOT_STEP_HEARD,
	E_PRIORITY_WHISTLING_HEARD,
	E_PRIORITY_SUSPICIOUS_ACTIVITY,
	E_PRIORITY_UNIDENTIFIED_PED,
	E_PRIORITY_REACTION_INVESTIGATE_DEAD_PED,
	E_PRIORITY_REACTION_INVESTIGATE_LOW_THREAT,
	E_PRIORITY_PED_LIKE,
	E_PRIORITY_PED_RESPECT,
	E_PRIORITY_PED_DISLIKE,
	// predict collisions
	E_PRIORITY_POTENTIAL_WALK_INTO_OBJECT,
	E_PRIORITY_POTENTIAL_BE_WALKED_INTO,
	E_PRIORITY_POTENTIAL_WALK_INTO_VEHICLE,
	// Shocking events that pose a potential threat
	E_PRIORITY_SHOCKING_EVENT_POTENTIALLY_DANGEROUS,
	// Confrontations
	E_PRIORITY_REQUEST_HELP_WITH_CONFRONTATION,
	// Agitated
	E_PRIORITY_AGITATED,
	E_PRIORITY_AGITATED_ACTION,
	// Higher priority shocking events, mostly those that pose an immediate threat
	E_PRIORITY_SHOCKING_EVENT_DANGEROUS,
	E_PRIORITY_SHOCKING_EVENT_SERIOUS_DANGER,
	// Script events
	E_PRIORITY_SCRIPT_WITH_DATA,
	E_PRIORITY_SCENARIO_FORCE_ACTION,
	E_PRIORITY_PED_WANTED,
	E_PRIORITY_PED_HATE_BADLY_LIT,
	E_PRIORITY_DISTURBANCE,
	E_PRIORITY_EXPLOSION_HEARD,
	E_PRIORITY_PED_HATE,
	E_PRIORITY_CRIME_CRY_FOR_HELP,
	E_PRIORITY_POTENTIAL_WALK_INTO_FIRE,
	// React to someone else's threat response
	E_PRIORITY_RESPONDED_TO_THREAT,
	// React to melee attacks (dramatic event)
	E_PRIORITY_MELEE_ACTION,
	// React to gun shots (dramatic event)
	E_PRIORITY_REVIVED_AFTER_REVIVED,
	E_PRIORITY_SHOT_FRIENDLY_NEAR_MISS,
	E_PRIORITY_SHOT_FIRED,
	E_PRIORITY_SHOT_FIRED_WHIZZED_BY,
	E_PRIORITY_SHOT_FIRED_BULLET_IMPACT,
	E_PRIORITY_REACTION_INVESTIGATE_HIGH_THREAT,
	// Events generated by reaction task
	E_PRIORITY_REACTION_ENEMY_PED,
	// Reaction to shouts from respected peds
	E_PRIORITY_SHOUT_BLOCKING_LOS,
	E_PRIORITY_SHOUT_TARGET_POSITION,
	E_PRIORITY_RADIO_TARGET_POSITION,
	E_PRIORITY_CALL_FOR_COVER,
	E_PRIORITY_PROVIDING_COVER,
	E_PRIORITY_INJURED_CALL_FOR_HELP,
	// React getting car jacked in some way
	E_PRIORITY_COP_CAR_BEING_STOLEN,
	E_PRIORITY_PED_JACKING_MY_VEHICLE,
	E_PRIORITY_PED_ENTERED_MY_VEHICLE,
	E_PRIORITY_DRAGGED_OUT_CAR,
	// High priority player commands
	E_PRIORITY_LEADER_HOLSTERED_WEAPON,
	E_PRIORITY_LEADER_UNHOLSTERED_WEAPON,
	E_PRIORITY_LEADER_ENTERED_COVER,
	E_PRIORITY_LEADER_LEFT_COVER,
	E_PRIORITY_MUST_LEAVE_BOAT,
	E_PRIORITY_LEADER_ENTERED_CAR_AS_DRIVER,		
	E_PRIORITY_LEADER_EXITED_CAR_AS_DRIVER,			    	
	E_PRIORITY_VEHICLE_DAMAGE,
	E_PRIORITY_FRIENDLY_AIMED_AT,
	E_PRIORITY_GUN_AIMED_AT,
	E_PRIORITY_POTENTIAL_GET_RUN_OVER,
	E_PRIORITY_POTENTIAL_BLAST,
	E_PRIORITY_EXPLOSION,
	E_PRIORITY_HELP_AMBIENT_FRIEND,
	E_PRIORITY_PLAYER_DEATH,
	// Car upside  down
	E_PRIORITY_CAR_UPSIDE_DOWN,
	// Script event
	E_PRIORITY_BLOCK_NON_TEMP_EVENTS,
	E_PRIORITY_NEW_TASK,
	E_PRIORITY_SCRIPT_COMMAND,
	E_PRIORITY_GIVE_PED_TASK,
	// Burning event
	E_PRIORITY_VEHICLE_ON_FIRE,
	// Bumped into something response
	E_PRIORITY_BUILDING_COLLISION,
	E_PRIORITY_VEHICLE_COLLISION,
	E_PRIORITY_PED_COLLISION_WITH_PED,
	// Physical events that take away control
	E_PRIORITY_IN_AIR,
	E_PRIORITY_IN_WATER,
	E_PRIORITY_GET_OUT_OF_WATER,
	// Stuck hanging in the air
	E_PRIORITY_STUCK_IN_AIR,
	// Physical events that do damage / move ped
	E_PRIORITY_DAMAGE,
	E_PRIORITY_HURT_TRANSITION,

	E_PRIORITY_DAMAGE_BY_MELEE,
	E_PRIORITY_ON_FIRE,

	// Time to climb a ladder during a route task.  Needs to be higher than damage events, or peds will never be able to navigate climbs & drops when chasing an attacker.
	E_PRIORITY_CLIMB_LADDER_ON_ROUTE,
	E_PRIORITY_CLIMB_NAVMESH_ON_ROUTE,
	// Stuck running into a wall.  Needs to be higher than damage events, or peds will never get unstuck when chasing an attacker.
	E_PRIORITY_STATIC_COUNT_REACHED_MAX,

	// Raise the priority of a damage event, if the ped is being attacked
	E_PRIORITY_DAMAGE_PAIRED_MOVE,

	E_PRIORITY_COMBAT_TAUNT,

	// Special script command that overrides nearly everything except nm
	E_PRIORITY_SCRIPT_COMMAND_SP_NO_NM,

	// Only allow nm behaviours to override nm getups. This prevents peds from popping up out of getup animations into standing
	// damage anims, etc
	E_PRIORITY_GETUP,

	E_PRIORITY_WRITHE,

	E_PRIORITY_SWITCH_2_NM,

	// Cuffed prevents everything except ragdoll
	E_PRIORITY_CUFFED,
	E_PRIORITY_INCUSTODY,

	// Raise the priority of a damage event, if the ped is ragdoll'ing
	E_PRIORITY_DAMAGE_WITH_RAGDOLL,
	// This is higher priority, the damage task will override it if 
	E_PRIORITY_SWITCH_2_NM_SCRIPT,

	// Special script command that overrides nearly everything else
	E_PRIORITY_SCRIPT_COMMAND_SP,
	// All over
	E_PRIORITY_INCAPACITATED,

	E_PRIORITY_DEATH,
	// Should be higher than an animated death
	E_PRIORITY_DEATH_WITH_RAGDOLL,
	// Dragged away by friendlies
	E_PRIORITY_DRAGGING,
	// New start in life
	E_PRIORITY_REVIVED,
	E_PRIORITY_MAX
};

#endif // INC_EVENT_PRIORITIES_H
