#include "Weapons/WeaponTypes.h"

// Generic
const atHashWithStringNotFinal WEAPONTYPE_DROWNING("WEAPON_DROWNING",0xFF58C4FB);
const atHashWithStringNotFinal WEAPONTYPE_DROWNINGINVEHICLE("WEAPON_DROWNING_IN_VEHICLE",0x736F5990);
const atHashWithStringNotFinal WEAPONTYPE_EXPLOSION("WEAPON_EXPLOSION",0x2024F4E8);
const atHashWithStringNotFinal WEAPONTYPE_FALL("WEAPON_FALL",0xCDC174B0);
const atHashWithStringNotFinal WEAPONTYPE_FIRE("WEAPON_FIRE",0xDF8E89EB);
const atHashWithStringNotFinal WEAPONTYPE_RAMMEDBYVEHICLE("WEAPON_RAMMED_BY_CAR",0x7FC7D7A);
const atHashWithStringNotFinal WEAPONTYPE_RUNOVERBYVEHICLE("WEAPON_RUN_OVER_BY_CAR",0xA36D413E);
const atHashWithStringNotFinal WEAPONTYPE_UNARMED("WEAPON_UNARMED",0xA2719263);
const atHashWithStringNotFinal WEAPONTYPE_BLEEDING("WEAPON_BLEEDING",0x8B7333FB);
const atHashWithStringNotFinal WEAPONTYPE_BUZZARD("VEHICLE_WEAPON_PLAYER_BUZZARD",0x46B89C8E);
const atHashWithStringNotFinal WEAPONTYPE_TANK("VEHICLE_WEAPON_TANK",0x73F7C04B);
const atHashWithStringNotFinal WEAPONTYPE_ROTORS("VEHICLE_WEAPON_ROTORS",0xB1205A4E);
const atHashWithStringNotFinal WEAPONTYPE_WATER_CANNON("WATER_CANNON",0x54C2B457);
const atHashWithStringNotFinal WEAPONTYPE_HIT_BY_WATER_CANNON("WEAPON_HIT_BY_WATER_CANNON",0xcc34325e);
const atHashWithStringNotFinal WEAPONTYPE_GOLFCLUB("WEAPON_GOLFCLUB",0x440E4788);
const atHashWithStringNotFinal WEAPONTYPE_ELECTRICFENCE("WEAPON_ELECTRIC_FENCE",0x92BD4EBB);
const atHashWithStringNotFinal WEAPONTYPE_EXHAUSTION("WEAPON_EXHAUSTION",0x364A29EC);
const atHashWithStringNotFinal WEAPONTYPE_MINIGUN("WEAPON_MINIGUN",0x42BF8A85);
const atHashWithStringNotFinal WEAPONTYPE_AIRSTRIKE_ROCKET("WEAPON_AIRSTRIKE_ROCKET",0x13579279);
const atHashWithStringNotFinal WEAPONTYPE_RPG("WEAPON_RPG",0xB1CA77B1);
const atHashWithStringNotFinal WEAPONTYPE_VEHICLE_PLAYER_BULLET("VEHICLE_WEAPON_PLAYER_BULLET", 0x4B139B2D);

//to be removed...
const atHashWithStringNotFinal WEAPONTYPE_ASSAULTRIFLE("WEAPON_ASSAULTRIFLE",0xBFEFFF6D);
const atHashWithStringNotFinal WEAPONTYPE_FIREEXTINGUISHER("WEAPON_FIREEXTINGUISHER",0x60EC506);
const atHashWithStringNotFinal WEAPONTYPE_GRENADE("WEAPON_GRENADE",0x93E220BD);
const atHashWithStringNotFinal WEAPONTYPE_GRENADELAUNCHER("WEAPON_GRENADELAUNCHER",0xA284510B);
const atHashWithStringNotFinal WEAPONTYPE_SMOKEGRENADE("WEAPON_SMOKEGRENADE",0xFDBC8A50);
const atHashWithStringNotFinal WEAPONTYPE_LOUDHAILER("WEAPON_LOUDHAILER",0xEB779748);
const atHashWithStringNotFinal WEAPONTYPE_PISTOL("WEAPON_PISTOL",0x1B06D571);
const atHashWithStringNotFinal WEAPONTYPE_STUNGUN("WEAPON_STUNGUN",0x3656C8C1);
const atHashWithStringNotFinal WEAPONTYPE_STICKYBOMB("WEAPON_STICKYBOMB",0x2c3731d9);
const atHashWithStringNotFinal WEAPONTYPE_DLC_PIPEBOMB("WEAPON_PIPEBOMB",0xba45e8b8);
const atHashWithStringNotFinal WEAPONTYPE_DLC_FIREWORK("WEAPON_FIREWORK",0x7F7497E5);
const atHashWithStringNotFinal WEAPONTYPE_DLC_PROXMINE("WEAPON_PROXMINE",0xAB564B93);
const atHashWithStringNotFinal WEAPONTYPE_DLC_SNOWBALL("WEAPON_SNOWBALL",0x0787f0bb);
const atHashWithStringNotFinal WEAPONTYPE_DLC_RAILGUN("WEAPON_RAILGUN",0x6D544C99);
const atHashWithStringNotFinal WEAPONTYPE_DLC_COMBATPDW("WEAPON_COMBATPDW",0x0A3D4D34);
const atHashWithStringNotFinal WEAPONTYPE_SCRIPT_HEALTH_CHANGE("WEAPONTYPE_SCRIPT_HEALTH_CHANGE",0x53e51e54);
const atHashWithStringNotFinal WEAPONTYPE_DLC_BOMB_GAS("VEHICLE_WEAPON_BOMB_GAS",0x5540A91E);
const atHashWithStringNotFinal WEAPONTYPE_DLC_TRANQUILIZER("WEAPON_TRANQUILIZER", 0x32A888BD);
const atHashWithStringNotFinal WEAPONTYPE_DLC_BZGAS_MK2("WEAPON_BZGAS_MK2",0x769C4F3E);
const atHashWithStringNotFinal WEAPONTYPE_VEHICLE_WEAPON_SUB_MISSILE_HOMING("VEHICLE_WEAPON_SUB_MISSILE_HOMING",0xaae74ac1);
const atHashWithStringNotFinal WEAPONTYPE_VEHICLE_WEAPON_OPPRESSOR2_MISSILE("VEHICLE_WEAPON_OPPRESSOR2_MISSILE", 0x753A78F1);


// Gadgets
const atHashWithStringNotFinal GADGETTYPE_SKIS("GADGET_SKIS",0xCA8D6330);
const atHashWithStringNotFinal GADGETTYPE_PARACHUTE("GADGET_PARACHUTE",0xFBAB5776);
const atHashWithStringNotFinal GADGETTYPE_JETPACK("GADGET_JETPACK",0x6a060d9c);

// Objects
const atHashWithStringNotFinal OBJECTTYPE_OBJECT("OBJECT",0x39958261);

// Ammos
const atHashWithStringNotFinal AMMOTYPE_STICKYBOMB("AMMO_STICKYBOMB",0x5424B617);
const atHashWithStringNotFinal AMMOTYPE_GRENADELAUNCHER("AMMO_GRENADELAUNCHER",0x3bcca5ee);
const atHashWithStringNotFinal AMMOTYPE_EMPLAUNCHER("AMMO_EMPLAUNCHER",0xF1DF48BD);
const atHashWithStringNotFinal AMMOTYPE_DLC_FLAREGUN("AMMO_FLAREGUN",0x45F0E965);

// Weapon groups
const atHashWithStringNotFinal WEAPONGROUP_PISTOL("GROUP_PISTOL",0x18D5FA97);
const atHashWithStringNotFinal WEAPONGROUP_SNIPER("GROUP_SNIPER",0xB7BBD827);
const atHashWithStringNotFinal WEAPONGROUP_SHOTGUN("GROUP_SHOTGUN",0x33431399);
const atHashWithStringNotFinal WEAPONGROUP_UNARMED("GROUP_UNARMED",0xA00FC1E4);
const atHashWithStringNotFinal WEAPONGROUP_RIFLE("GROUP_RIFLE",0x39D5C192);
const atHashWithStringNotFinal WEAPONGROUP_SMG("GROUP_SMG",0xC6E9A5C5);
const atHashWithStringNotFinal WEAPONGROUP_MG("GROUP_MG",0x451B04BC);
const atHashWithStringNotFinal WEAPONGROUP_RUBBERGUN("GROUP_RUBBERGUN",0x54C7FFC);
const atHashWithStringNotFinal WEAPONGROUP_LOUDHAILER("GROUP_LOUDHAILER",0x1E3DEED0);
const atHashWithStringNotFinal WEAPONGROUP_HEAVY("GROUP_HEAVY",0xA27A4F9F);
const atHashWithStringNotFinal WEAPONGROUP_MELEE("GROUP_MELEE", 0xD49321D4);
const atHashWithStringNotFinal WEAPONGROUP_PETROLCAN("GROUP_PETROLCAN", 0x5f1be07c);
const atHashWithStringNotFinal WEAPONGROUP_THROWN("GROUP_THROWN", 0x5c4c5883);

// Firing patterns
const atHashWithStringNotFinal FIRING_PATTERN_BURST_FIRE("FIRING_PATTERN_BURST_FIRE",0xD6FF6D61);
const atHashWithStringNotFinal FIRING_PATTERN_BURST_FIRE_IN_COVER("FIRING_PATTERN_BURST_FIRE_IN_COVER",0x26321F1);
const atHashWithStringNotFinal FIRING_PATTERN_FULL_AUTO("FIRING_PATTERN_FULL_AUTO",0xC6EE6B4C);
const atHashWithStringNotFinal FIRING_PATTERN_SINGLE_SHOT("FIRING_PATTERN_SINGLE_SHOT",0x5D60E4E0);
const atHashWithStringNotFinal FIRING_PATTERN_DELAY_FIRE_BY_ONE_SEC("FIRING_PATTERN_DELAY_FIRE_BY_ONE_SEC",0x7A845691);
const atHashWithStringNotFinal FIRING_PATTERN_FROM_GROUND("FIRING_PATTERN_FROM_GROUND",0x2264E5D6);
