#ifndef _REPLAYPACKETIDS_H_
#define _REPLAYPACKETIDS_H_


#if GTA_REPLAY

#include "system/memops.h"

struct packetInfo
{
	packetInfo()
	: count(0)
	, size(0)
	{
		sysMemSet(name, 0, sizeof(name));
	}
	char name[64];
	int	count;
	int size;
};
enum eReplayPacketId
{
	PACKETID_END = 0,	// Used to indicate the end of the buffer
	PACKETID_END_HISTORY,	// REMOVE?
	// NOTE: The IDs are sectioned into groups that start with a MIN ID and end with a MAX ID.
	//        Each group represents a bit in a u32 bit flag that is used to filter out which
	//        packets can be played. See ReplayMgr::PlayBackHistory().
	// WARNING: We can only have 32 groups unless we switch the bit flag from a u32 to a u64.
	PACKETID_ALIGN,	

	// Game related
	PACKETID_GAME_MIN,
	PACKETID_CAMERAUPDATE,
	PACKETID_CLOCK,
	PACKETID_WEATHER,
	PACKETID_WATERSIMULATE,
	PACKETID_NEXTFRAME,
	PACKETID_GAMETIME,	
	PACKETID_GAME_MAX,

	// Vehicle related
	// Always put new vehicle types between the delete packet and the wheel update IDs
	PACKETID_VEHICLE_MIN,
	PACKETID_VEHICLECREATE,
	PACKETID_VEHICLEUPDATE,
	PACKETID_VEHICLEDELETE,

	// The vehicle interface sometimes checks update packet ID's are within this range...
	// If any changes are made here make sure those checks match up.
	PACKETID_CARUPDATE,
	PACKETID_BICYCLEUPDATE,
	PACKETID_BIKEUPDATE,
	PACKETID_BOATUPDATE,
	PACKETID_HELIUPDATE,
	PACKETID_AUTOGYROUPDATE,
	PACKETID_BLIMPUDPATE,
	PACKETID_PLANEUPDATE,
	PACKETID_QUADBIKEUPDATE,
	PACKETID_TRAILERUPDATE,
	PACKETID_TRAINUPDATE,
	PACKETID_SUBUPDATE,

	PACKETID_WHEELUPDATE_OLD,
	PACKETID_DOORUPDATE,
	PACKETID_MODBONE_UPDATE,	
	PACKETID_VEHICLE_MAX,

	PACKETID_WHEEL,
	PACKETID_VEHVARIATIONCHANGE,

	// Building related
	PACKETID_BUILDING_MIN,
	PACKETID_PLANEDELETE,
	PACKETID_CARRIAGEUPDATE,
	PACKETID_CARRIAGEDELETE,
	PACKETID_BUILDING_MAX,

	PACKETID_ENTITY_DELETE,

	// Ped related
	PACKETID_PED_MIN,
	PACKETID_PEDUPDATE,
	PACKETID_PEDCREATE,
	PACKETID_PEDDELETE,
	PACKETID_PED_MAX,

	PACKETID_PEDHEADBLENDCHANGE,
	PACKETID_PEDMICROMORPHCHANGE,
	PACKETID_PEDVARIATIONCHANGE,	

	// Object related
	PACKETID_OBJECT_MIN,
	PACKETID_OBJECTCREATE,

	PACKETID_OBJECTUPDATE,
	PACKETID_OBJECTDOORUPDATE,

	PACKETID_OBJECTDELETE,

	PACKETID_OBJECTHIDDENMAP,	
	PACKETID_OBJECT_MAX,

	PACKETID_DESTROYED_MAP_OBJECTS_FOR_CLIP_START,
	PACKETID_OBJECT_SNIPED,

	// pickup related
	PACKETID_PICKUP_MIN,
	PACKETID_PICKUP_CREATE,
	PACKETID_PICKUP_UPDATE,
	PACKETID_PICKUP_DELETE,
	PACKETID_PICKUP_MAX,

	// Fragment related
	PACKETID_FRAG_MIN,
	PACKETID_FRAGDATA,
	PACKETID_FRAGBONEDATA,
	PACKETID_FRAGBONEDATA_USINGSKELETONPACKETS,
	PACKETID_SKELETONBONEDATA,
	PACKETID_FRAG_MAX,

	// Pfx related
	PACKETID_PARTICLE_MIN,
	PACKETID_PARTICLE,
	PACKETID_EVOLVEPTFX,

	/// Pfx Peds
	PACKETID_PEDBREATHFX,		// To fix: ped bone data?
	PACKETID_PEDSMOKEFX,		// To fix: ped bone data?
	PACKETID_PEDFOOTFX,			// To fix: ped bone data?
	PACKETID_PLAYERSWITCH,
	/// Pfx Vehs
	PACKETID_VEHBACKFIREFX,		// Prerender
	PACKETID_VEHOVERHEATFX,		// Prerender
	PACKETID_VEHPETROLTANKFX,		// Process control
	PACKETID_VEHHEADLIGHTSMASHFX,	// Process control
	PACKETID_VEHRESPRAYFX,			// Process control
	PACKETID_VEHTYREPUNCTUREFX,		// Process control
	PACKETID_VEHTYREFIREFX,			// Process control
	PACKETID_VEHTYREBURSTFX,		// Process control
	PACKETID_VEHICLEDMGUPDATE,
	PACKETID_VEHICLESLIPSTREAMFX,
	/////
	PACKETID_TRAINSPARKSFX,		// - Prerender2
	PACKETID_HELIDOWNWASHFX,
	PACKETID_HELIPARTSDESTROYFX,
	PACKETID_VEHPARTFX,

	/// Pfx Fire
	PACKETID_FIREFX,			// VisualEffects::Update
	PACKETID_FIREPEDFX,			// VisualEffects::Update
	PACKETID_FIRESTEAMFX,		// VisualEffects::PostPreRender
	PACKETID_FIRESMOKEPEDFX,	// To fix: ped bone data?
	PACKETID_FIREVEHWRECKEDFX,	// VisualEffects::Update
	PACKETID_FIREENTITYFX,		// VisualEffects::Update
	PACKETID_EXPLOSIONFX, 		// VisualEffects::Update
	// Pfx Weapon
	PACKETID_WEAPONBULLETIMPACTFX,
	PACKETID_WEAPONMUZZLEFLASHFX,
	PACKETID_WEAPONMUZZLESMOKEFX,
	PACKETID_WEAPONBULLETTRACEFX,
	PACKETID_WEAPONEXPLOSIONFX_OLD,
	PACKETID_WEAPONEXPLOSIONWATERFX,
	PACKETID_WEAPONVOLUMETRICFX,
	PACKETID_WEAPONFLASHLIGHT,
	PACKETID_WEAPONPROJTRAILFX,
	PACKETID_WEAPONGUNSHELLFX,
	// Pfx Blood
	PACKETID_BLOODFX,			// To fix: ped bone data?
	PACKETID_BLOODDECAL,
	PACKETID_BLOODMOUTHFX,		// To fix: ped bone data?
	PACKETID_BLOODFALLDEATHFX,
	//PACKETID_BLOODPOOLFX,
	PACKETID_BLOODWHEELFX,
	PACKETID_BLOODPIGEONFX,
	//Pfx Entity
	PACKETID_ENTITYANIMTRIGFX, //TO Remove
	PACKETID_ENTITYANIMUPDTFX, //TO Remove
	PACKETID_ENTITYFRAGBREAKFX,
	PACKETID_ENTITYSHOTFX_OLD,
	PACKETID_ENTITYAMBIENTFX,
	PACKETID_ENTITYFRAGDESTROYFX, //TO Remove
	PACKETID_ENTITYCOLLISIONFX,
	// Pfx Mark
	PACKETID_MARKSCRAPEFX,
	PACKETID_MARKSKIDFX,
	// Pfx Material
	PACKETID_MATERIALBANGFX,
	// Pfx Misc
	PACKETID_GLASSGROUNDFX,
	PACKETID_GLASSSMASHFX,
	PACKETID_TRAFFICLIGHTOVERRIDE,
	PACKETID_STARTSCRIPTFX,
	PACKETID_STOPSCRIPTFX,
	PACKETID_UPDATEOFFSETSCRIPTFX,
	PACKETID_TRIGGEREDSCRIPTFX,
	PACKETID_PARACUTESMOKE,
	PACKETID_REQUESTPTFXASSET,
	// Pfx Water
	PACKETID_WATERBOATENTRYFX,
	PACKETID_WATERSPLASHHELIFX,
	PACKETID_WATERSPLASHGENERICFX,
	PACKETID_WATERSPLASHVEHICLEFX,
	PACKETID_WATERSPLASHVEHICLETRAILFX,
	PACKETID_WATERBOATWASHFX,
	PACKETID_WATERSPLASHPEDFX,
	PACKETID_WATERSPLASHPEDOUTFX,
	PACKETID_WATERSPLASHPEDINFX,
	PACKETID_WATERBOATBOWFX,
	PACKETID_WATERSPLASHPEDWADEFX,
	PACKETID_WATERSPLASHVEHWADEFX,
	PACKETID_WATERCANNONSPRAYFX,
	PACKETID_WATERCANNONJETFX,
	PACKETID_WATERFOAM,
	PACKETID_CUBIC_PATCH_WATERFRAME,
	// Pfx Ripple
	PACKETID_RIPPLEWAKEFX,
	PACKETID_DYNAMICWAVEFX,
	PACKETID_PLANEWINGTIPFX,
	PACKETID_UPDATESCRIPTFXFARCLIPDIST,
	PACKETID_PROJECTILEFX,
	PACKETID_SUBDIVEFX,
	PACKETID_UPDATESCRIPTFXCOLOUR,
	PACKETID_PARTICLE_MAX,
	// Lightning
	PACKETID_DIRECTIONALLIGHTNING,
	PACKETID_CLOUDLIGHTNING,
	PACKETID_LIGHTNINGSTRIKE,

	// Proj. Textures
	PACKETID_PTEX_MIN,
	PACKETID_PTEXBLOODPOOL,
	PACKETID_PEDBLOODDAMAGE,
	PACKETID_PEDBLOODDAMAGESCRIPT,
	PACKETID_PTEXWEAPONSHOT,
	PACKETID_PTEXFOOTPRINT,
	PACKETID_PTEXMTLBANG,
	PACKETID_PTEXMTLSCRAPE,
	PACKETID_DECALSREMOVE,
	PACKETID_SCRIPTDECALADD,
	PACKETID_SCRIPTDECALREMOVE,
	PACKETID_PTEX_MAX,
	PACKETID_TRAILDECAL,

	//Rope
	PACKETID_ADDROPE_OLD,	//TO Remove
	PACKETID_DELETEROPE_OLD,	//TO Remove
	PACKETID_ATTACHROPETOENTITY,
	PACKETID_ATTACHENTITIESTOROPE,
	PACKETID_DETACHROPEFROMENTITY_OLD,	//TO Remove
	PACKETID_ATTACHOBJECTSTOROPEARRAY,
	PACKETID_PINROPE,
	PACKETID_UNPINROPE,
	PACKETID_RAPPELPINROPE,
	PACKETID_LOADROPEDATA,
	PACKETID_ROPEWINDING,
	PACKETID_ROPEUPDATEORDER,

	// Audio Packets
	PACKETID_SOUND_MIN,
	PACKETID_SOUND_AUTOMATIC,
	PACKETID_SOUND_BREATH,
	PACKETID_SOUND_BULLETBY,
	PACKETID_SOUND_EXPLOSIONBULLETBY,
	PACKETID_SOUND_BULLETIMPACT,
	PACKETID_SOUND_PLAYERWEAPONREPORT,
	PACKETID_SOUND_COLLISIONPLAY,
	PACKETID_SOUND_COLLISIONUPDATE,
	PACKETID_SOUND_CREATE,
	PACKETID_SOUND_CREATE_MISC_OLD,
	PACKETID_SOUND_CREATE_POSITION,
	PACKETID_SOUND_CREATE_AND_PLAY,
	PACKETID_SOUND_CREATE_AND_PLAY_PERSIST,
	PACKETID_SOUND_PHONE_RING,
	PACKETID_SOUND_STOP_PHONE_RING,
	PACKETID_SOUND_PRESUCK,
	PACKETID_SOUND_EXPLOSION,
	PACKETID_SOUND_FIRE_INIT,
	PACKETID_SOUND_FIRE_UPDATE,
	PACKETID_SOUND_FIRE_VEHICLE_UPDATE,
	PACKETID_SOUND_PEDFOOTSTEP,
	PACKETID_SOUND_PEDBUSH,
	PACKETID_SOUND_PEDCLOTH,
	PACKETID_SOUND_PEDPETROLCAN,
	PACKETID_SOUND_PEDMOLOTOV,
	PACKETID_SOUND_PEDWATER,
	PACKETID_SOUND_PEDSLOPEDEBRIS,
	PACKETID_SOUND_PEDSTANDINMATERIAL,
	PACKETID_SOUND_PROJECTILE,
	PACKETID_SOUND_PROJECTILESTOP,
	PACKETID_SOUND_PEDFALLTODEATH,
	PACKETID_SOUND_MELEE,
	PACKETID_SOUND_STOP,
	PACKETID_SOUND_START,
	PACKETID_SOUND_UPDATE_AND_PLAY,
	PACKETID_SOUND_LPF_CUTOFF,
	PACKETID_SOUND_UPDATE_PITCH,
	PACKETID_SOUND_PITCH_POS,
	PACKETID_SOUND_PITCH_POS_VOL,
	PACKETID_SOUND_PITCH_VOL,
	PACKETID_SOUND_POS,
	PACKETID_SOUND_POS_VOL,
	PACKETID_SOUND_POST_SUBMIX,
	PACKETID_SOUND_UPDATE_SETTINGS,
	PACKETID_SOUND_UPDATE_VOLUME,
	PACKETID_SOUND_UPDATE_DOPPLER,
	PACKETID_SOUND_SET_VALUE_DH,
	PACKETID_SOUND_SET_CLIENT_VAR,
	PACKETID_SOUND_VEHICLE_PED_COLLSION,
	PACKETID_SOUND_PED_IMPACT_COLLSION,
	PACKETID_SOUND_WEAPON_FIRE_EVENT_OLD,
	PACKETID_SOUND_WEAPON_PERSIST,
	PACKETID_SOUND_WEAPON_PERSIST_STOP,
	PACKETID_SOUND_WEAPON_SPINUP,
	PACKETID_SOUND_WEAPON_ECHO,
	PACKETID_SOUND_SPEECH,
	PACKETID_SOUND_SPEECH_PAIN,
	PACKETID_SOUND_SPEECH_STOP,
	PACKETID_SOUND_SPEECH_SAY,
	PACKETID_SOUND_SPEECH_SCRIPTED,
	PACKETID_SOUND_SPEECH_SCRIPTED_UPDATE,
	PACKETID_SOUND_SPEECH_ANIMAL,
	PACKETID_SOUND_PLAYPRELOADEDSPEECH,
	PACKETID_SOUND_CUTSCENE,
	PACKETID_SOUND_CUTSCENE_STOP,
	PACKETID_SOUND_SYNCHSCENE,
	PACKETID_SOUND_SYNCHSCENE_STOP,
	PACKETID_SOUND_VEHICLE_HORN,
	PACKETID_SOUND_VEHICLE_HORN_STOP,
	PACKETID_SOUND_VEHICLE_SPLASH,
	PACKETID_SOUND_SCRIPTSWEETENER,
	PACKETID_SND_LOADWEAPONDATA,
	PACKETID_SND_PAINWAVEBANKCHANGE,
	PACKETID_SND_SETPLAYERPAINROOT,
	PACKETID_SND_PLAYSTREAMFROMENTITY,
	PACKETID_SND_PLAYSTREAMFROMPOSITION,
	PACKETID_SND_PLAYSTREAMFRONTED,
	PACKETID_SND_STOPSTREAM,
	PACKETID_SND_LOADSCRIPTBANK,
	PACKETID_DYNAMICMIXER_SCENE,
	PACKETID_PORTAL_OCCLUSION_OVERRIDES,
	PACKETID_MODIFIED_AMBIENT_ZONE_STATES,
	PACKETID_SOUND_SET_VARIABLE_ON_SOUND,
	PACKETID_SOUND_UPDATE_PERSIST,
	PACKETID_ACTIVE_ALARMS,
	PACKETID_SND_LOADSCRIPTWAVEBANK,
	PACKETID_SET_AUDIO_SCENE_VARIABLE,
	PACKETID_SOUND_MAX,

	PACKETID_SMASH_MIN,
	PACKETID_SMASHABLEEXPLOSION,
	PACKETID_SMASHABLECOLLISION,
	PACKETID_SMASH_MAX,

	PACKETID_SOUND2_MIN,
	PACKETID_SOUND2_MAX,

	PACKETID_SCRIPTEDFX,
	PACKETID_ANIMATEDOBJDATA,
	PACKETID_SCRIPTEDBUILDINGSWAP,
	PACKETID_SCRIPTEDUPDATEFX,
	PACKETID_TRIGGEREDSCRIPTFXCOLOUR,

	PACKETID_GLASS_CREATEBREAKABLEGLASS,
	PACKETID_GLASS_HIT,

	PACKETID_MOVIE,
	PACKETID_MOVIE_TARGET,
	PACKETID_MOVIE_ENTITY,

	PACKETID_IPL,
	PACKETID_INTERIOR_PROXY_STATE,
	PACKETID_FORCE_ROOM_FOR_GAMEVIEWPORT,	
	PACKETID_INTERIOR,
	PACKETID_INTERIOR_ENTITY_SET,
	PACKETID_MAP_CHANGE,
	PACKETID_MESH_SET,

	PACKETID_RAYFIRE_STATIC,
	PACKETID_RAYFIRE_PRE_LOAD,
	PACKETID_RAYFIRE_UPDATING,

	PACKETID_TC_SCRIPT_MODIFIER,

	PACKETID_REQUESTCLOUDHAT,
	PACKETID_UNLOADALLCLOUDHATS,	
	PACKETID_WEAPON_THERMAL_VISION,

	//Cutscene
	PACKETID_CUTSCENELIGHT,
	PACKETID_CUTSCENECHARACTERLIGHTPARAMS,
	PACKETID_CUTSCENECAMERAARGS,
	PACKETID_CUTSCENE_NONRP_OBJECT_HIDE,

	//Lighting
	PACKETID_LIGHT_BROKEN,
	PACKETID_PED_LIGHT,
	PACKETID_PHONE_LIGHT,

	PACKETID_FRAME,	

	// More particle effects
	PACKETID_PTFX_FRAGMENTDESTROY,
	PACKETID_DECAL_FRAGMENTDESTROY,

	//Add new packets here
	PACKETID_GLASS_TRANSFER,
	PACKETID_TOWTRUCKARMROTATE,
	PACKETID_PTEXMTLSCRAPE_PLAYERVEH,
	PACKETID_PTEXMTLBANG_PLAYERVEH,
	PACKETID_VEHICLEDMGUPDATE_PLAYERVEH,
	PACKETID_DISTANTCARSTATE,
	PACKETID_TIMECYCLE_MODIFIER,

	PACKETID_ENTITYATTACHDETACH,
	PACKETID_AUD_PED_SCENARIOS,

	PACKETID_FRAGDATA_NO_DAMAGE_BITS,

	PACKETID_ADDROPE,
	PACKETID_DELETEROPE,
	PACKETID_DETACHROPEFROMENTITY,

	PACKETID_MODEL_CULL,				// Now replaced with functionality in PACKETID_DISABLED_THIS_FRAME
	PACKETID_DISABLE_OCCLUSION,			// Now replaced with functionality in PACKETID_DISABLED_THIS_FRAME

	PACKETID_DISABLE_DECAL_RENDERING,
	PACKETID_TRACKED_FIREFX,
	PACKETID_BLOODSHARKBITEFX,

	PACKETID_FORCE_ROOM_FOR_ENTITY_OLD,
	PACKETID_CLOTH_PIECES,
	PACKETID_FORCE_ROOM_FOR_ENTITY,
	// More audio stuff
	PACKETID_SET_UNDERWATER_STREAM_VARIABLE,
	PACKETID_SET_OVERRIDE_UNDERWATER_STREAM,
	PACKETID_SET_SCRIPT_AUDIO_FLAGS,

	PACKETID_TRACKED_STOPFIREFX,

	PACKETID_ENTITYSHOTFX,
	PACKETID_SOUND_CREATE_MISC,
	PACKETID_BRIEF_LIFETIME_DESTROYED_MAP_OBJECTS,
	PACKETID_SOUND_WEAPON_FIRE_EVENT,
	PACKETID_WEAPONEXPLOSIONFX,
	PACKETID_VEHICLE_BADGE_REQUEST,
	PACKETID_SOUND_SPECIAL_EFFECT_MODE,

	PACKETID_DISABLED_THIS_FRAME,
	PACKETID_STARTNETWORKSCRIPTFX,
	PACKETID_FORCEVEHINTERIORSCRIPTFX,
	PACKETID_DESTROYSCRIPTFX,

	PACKETID_REGVEHICLEFIRE,

	PACKETID_WEAPONBULLETTRACEFX2,

	PACKETID_SOUND_CREATE_MISC_W_VAR,

	PACKETID_REQUESTNAMEDPTFXASSET,

	PACKETID_THERMALVISIONVALUES,

	PACKETID_SETDUMMYOBJECTTINT,

	PACKETID_ADDSNOWBALLDECAL,

	PACKETID_INTERIOR_ENTITY_SET2,

	PACKETID_REGISTERANDLINKRENDERTARGET,
	PACKETID_SETGFXALIGN,
	PACKETID_SETRENDER,
	PACKETID_DRAWSPRITE,

	PACKETID_TRAILPOLYSFRAME,

	PACKETID_AMPHAUTOUPDATE,
	PACKETID_AMPHQUADUPDATE,

	PACKETID_SETOBJECTTINT, 

	PACKETID_VEHICLEJUMPRECHARGE,

	PACKETID_SETBUILDINGTINT, 

	PACKETID_SOUND_BULLETIMPACT_NEW,
	PACKETID_SOUND_THERMAL_SCOPE,

	PACKETID_FOCUSENTITY,

	PACKETID_SOUND_WEAPON_AUTO_FIRE_STOP,

	PACKETID_FRAGBONEDATA_USINGSKELETONPACKETS_HIGHQUALITY,
	PACKETID_SKELETONBONEDATA_HIGHQUALITY,

	PACKETID_SUBCARUPDATE,

	PACKETID_VEHICLE_WEAPON_CHARGE,

	PACKETID_FOCUSPOSANDVEL,

	PACKETID_OVERRIDEOBJECTLIGHTCOLOUR,

	PACKETID_SOUND_VEHICLE_NITROUS_ACTIVE,

	PACKETID_REGISTER_RENDERTARGET,
	PACKETID_LINK_RENDERTARGET,
	PACKETID_DRAWMOVIE,
	PACKETID_MOVIE2,

	PACKETID_DRAWSPRITE2,
	PACKETID_PER_PORTAL_OCCLUSION_OVERRIDES,

	PACKETID_INVALID, //Keep these at the end
	PACKETID_MAX //Keep these at the end
};

CompileTimeAssert(PACKETID_INVALID <= 65535);

#endif // GTA_REPLAY


#endif // _REPLAYPACKETIDS_H_
