<?xml version="1.0"?>
<ParserSchema xmlns="http://www.rockstargames.com/RageParserSchema"
              generate="class">

 <hinclude>
    "atl/bitset.h"
 </hinclude>
	
  <enumdef type="CWeaponInfoFlags::Flags" generate="bitset">
    <enumval name="CarriedInHand"/>
    <enumval name="Automatic"/>
    <enumval name="Silenced"/>
    <enumval name="FirstPersonScope"/>
    <enumval name="ArmourPenetrating"/>
    <enumval name="ApplyBulletForce"/>
    <enumval name="Gun"/>
    <enumval name="CanLockonOnFoot"/>
    <enumval name="CanLockonInVehicle"/>
    <enumval name="Homing"/>
    <enumval name="CanFreeAim"/>
    <enumval name="Heavy"/>
    <enumval name="TwoHanded"/>
    <enumval name="Launched"/>
    <enumval name="MeleeBlade"/>
    <enumval name="MeleeClub"/>
    <enumval name="AnimReload"/>
    <enumval name="AnimCrouchFire"/>
    <enumval name="CreateVisibleOrdnance"/>
    <enumval name="TreatAsOneHandedInCover"/>
    <enumval name="TreatAsTwoHandedInCover"/>
    <enumval name="Thrown"/>
    <enumval name="Bomb"/>
    <enumval name="UsableOnFoot"/>
    <enumval name="UsableUnderwater"/>
    <enumval name="UsableClimbing"/>
    <enumval name="UsableInCover"/>
    <enumval name="AllowEarlyExitFromFireAnimAfterBulletFired"/>
    <enumval name="DisableRightHandIk"/>
    <enumval name="DisableLeftHandIkInCover"/>
    <enumval name="DontSwapWeaponIfNoAmmo"/>
    <enumval name="UseLoopedReloadAnim"/>
    <enumval name="DoesRevivableDamage"/>
    <enumval name="NoFriendlyFireDamage"/>
    <enumval name="Detonator"/>
    <enumval name="DisplayRechargeTimeHUD"/>
    <enumval name="OnlyFireOneShot"/>
    <enumval name="OnlyFireOneShotPerTriggerPress"/>
    <enumval name="UseLegDamageVoice"/>
    <enumval name="Lasso"/>
    <enumval name="CanBeFiredLikeGun"/>
    <enumval name="OnlyAllowFiring"/>
    <enumval name="NoLeftHandIK"/>
    <enumval name="NoLeftHandIKWhenBlocked"/>
    <enumval name="RiotShield"/>
    <enumval name="IgnoreStrafing"/>
    <enumval name="Vehicle"/>
    <enumval name="EnforceAimingRestrictions"/>
    <enumval name="ForceEjectShellAfterFiring"/>
    <enumval name="NonViolent"/>
    <enumval name="NonLethal"/>
    <enumval name="Scary"/>
    <enumval name="AllowCloseQuarterKills"/>
    <enumval name="DisablePlayerBlockingInMP"/>
    <enumval name="StaticReticulePosition"/>
    <enumval name="CanPerformArrest"/>
    <enumval name="DiscardWhenSwapped"/>
    <enumval name="AllowMeleeIntroAnim"/>
    <enumval name="ManualDetonation"/>
    <enumval name="SuppressGunshotEvent"/>
    <enumval name="HiddenFromWeaponWheel"/>
    <enumval name="AllowDriverLockOnToAmbientPeds"/>
    <enumval name="NeedsGunCockingInCover"/>
    <enumval name="ThrowOnly"/>
    <enumval name="NoAutoRunWhenFiring"/>
    <enumval name="DisableIdleVariations"/>
    <enumval name="HasLowCoverReloads"/>
    <enumval name="HasLowCoverSwaps"/>
    <enumval name="DontBreakRopes"/>
    <enumval name="CookWhileAiming"/>
    <enumval name="UseLeftHandIkWhenAiming"/>
    <enumval name="DropWhenCooked"/>
    <enumval name="NotAWeapon"/>
    <enumval name="RemoveEarlyWhenEnteringVehicles"/>
    <enumval name="DontBlendFireOutro"/>
    <enumval name="DiscardWhenOutOfAmmo"/>
    <enumval name="DelayedFiringAfterAutoSwap"/>
    <enumval name="EnforceFiringAngularThreshold"/>
    <enumval name="ForcesActionMode"/>
    <enumval name="CreatesAPotentialExplosionEventWhenFired"/>
    <enumval name="CreateBulletExplosionWhenOutOfTime"/>
    <enumval name="DelayedFiringAfterAutoSwapPreviousWeapon"/>
    <enumval name="DisableCombatRoll"/>
    <enumval name="NoWheelStats"/>
    <enumval name="ProcessGripAnim"/>
    <enumval name="DisableStealth"/>
    <enumval name="DangerousLookingMeleeWeapon"/>
    <enumval name="QuitTransitionToIdleIntroOnWeaponChange"/>
    <enumval name="DisableLeftHandIkWhenOnFoot"/>
    <enumval name="IgnoreHelmets"/>
    <enumval name="Rpg"/>
    <enumval name="NoAmmoDisplay"/>
    <enumval name="TorsoIKForWeaponBlock"/>
    <enumval name="LongWeapon"/>
    <enumval name="UsableUnderwaterOnly"/>
    <enumval name="MeleeKungFu"/>
    <enumval name="ForceDriveByAssistedAim"/>
    <enumval name="AssistedAimVehicleWeapon"/>
    <enumval name="CanBlowUpVehicleAtZeroBodyHealth"/>
    <enumval name="IgnoreAnimReloadRateModifiers"/>
    <enumval name="DisableIdleAnimationFilter"/>
    <enumval name="PenetrateVehicles"/>
    <enumval name="ScalesDamageBasedOnMaxVehicleHealth"/>
    <enumval name="HomingToggle"/>
    <enumval name="ApplyVehicleDamageToEngine"/>
    <enumval name="Turret"/>
    <enumval name="DisableAimAngleChecksForReticule"/>
    <enumval name="AllowMovementDuringFirstPersonScope"/>
    <enumval name="DriveByMPOnly"/>
    <enumval name="PlacedOnly" />
    <enumval name="CreateWeaponWithNoModel" />
    <enumval name="RemoveWhenUnequipped" />
    <enumval name="BlockAmbientIdles" />
    <enumval name="NotUnarmed" />
    <enumval name="UseFPSAimIK"/>
    <enumval name="DisableFPSScope"/>
    <enumval name="DisableFPSAimForScope"/>
    <enumval name="EnableFPSRNGOnly"/>
    <enumval name="EnableFPSIdleOnly"/>
    <enumval name="MeleeHatchet"/>
    <enumval name="UseAlternateFPDrivebyClipset"/>
    <enumval name="AttachFPSLeftHandIKToRight"/>
    <enumval name="OnlyUseAimingInfoInFPS"/>
    <enumval name="UseFPSAnimatedRecoil"/>
    <enumval name="UseFPSSecondaryMotion"/>
    <enumval name="HasFPSProjectileWeaponAnims"/>
    <enumval name="AllowMeleeBlock"/>
    <enumval name="DontPlayDryFireAnim"/>
 	<enumval name="SwapToUnarmedWhenOutOfThrownAmmo" />
	<enumval name="PlayOutOfAmmoAnim"/>
    <enumval name="DisableIdleAnimationFilterWhenReloading"/>
    <enumval name="OnFootHoming"/>
    <enumval name="DamageCausesDisputes"/>
    <enumval name="UsePlaneExplosionDamageCapInMP"/>
    <enumval name="FPSOnlyExitFireAnimAfterRecoilEnds"/>
    <enumval name="SkipVehiclePetrolTankDamage"/>
    <enumval name="DontAutoSwapOnPickUp"/>
    <enumval name="DisableTorsoIKAboveAngleThreshold"/>
    <enumval name="MeleeFist"/>
    <enumval name="NotAllowedForDriveby"/>
	<enumval name="AttachReloadObjectToRightHand"/>
    <enumval name="CanBeAimedLikeGunWithoutFiring" />
    <enumval name="MeleeMachete" />
    <enumval name="HideReticule" />
    <enumval name="UseHolsterAnimation" />
    <enumval name="BlockFirstPersonStateTransitionWhileFiring" />
    <enumval name="ForceFullFireAnimation" />
    <enumval name="DisableLeftHandIkInDriveby"/>
    <enumval name="CanUseInVehMelee"/>
    <enumval name="UseVehicleWeaponBoneForward"/>
    <enumval name="UseManualTargetingMode"/>
    <enumval name="IgnoreTracerVfxMuzzleDirectionCheck"/>
    <enumval name="IgnoreHomingCloseThresholdCheck"/>
    <enumval name="LockOnRequiresAim"/>
    <enumval name="DisableCameraPullAround"/>
    <enumval name="VehicleChargedLaunch"/>
    <enumval name="ForcePedAsFiringEntity"/>
    <enumval name="FiringEntityIgnoresExplosionDamage"/>
    <enumval name="IdlePhaseBasedOnTrigger"/>
    <enumval name="HighSpinRate"/>
    <enumval name="EnabledOnlyWhenVehTransformed"/>
    <enumval name="IncendiaryGuaranteedChance"/>
    <enumval name="UseCameraHeadingForHomingTargetCheck"/>
    <enumval name="UseWeaponRangeForTargetProbe"/>
    <enumval name="SkipProjectileLOSCheck"/>
    <enumval name="UseRevolverBehaviour"/>
    <enumval name="UseSingleActionBehaviour"/>
    <enumval name="PairedWeaponHolsterAnimation" />
    <enumval name="UseInstantAnimBlendFromIdleToFire"/>
    <enumval name="UseInstantAnimBlendFromFireToIdle" />
    <enumval name="BlockRagdollResponseTaskForPlayer" />
    <enumval name="FireAnimRateScaledToTimeBetweenShots"/>
    <enumval name="DamageOverTimeShockedEffect"/>
    <enumval name="DamageOverTimeChokingEffect"/>
    <enumval name="DamageOverTimeAllowStacking"/>
    <enumval name="BoatWeaponIsNotSearchLight"/>
    <enumval name="AllowFireInterruptWhenReady"/>
    <enumval name="ResponsiveRecoilRecovery"/>
    <enumval name="OnlyLockOnToAquaticVehicles"/>
  </enumdef>

</ParserSchema>
