#include "ai\debug\types\VehicleFlagDebugInfo.h"

#if AI_DEBUG_OUTPUT_ENABLED

#include "fragment/type.h"
#include "vehicles\vehicle.h"
#include "vehicleAi\VehicleIntelligence.h"

CVehicleFlagDebugInfo::CVehicleFlagDebugInfo(const CVehicle* pVeh, DebugInfoPrintParams printParams, s32 iNumberOfLines)
: CVehicleDebugInfo(pVeh, printParams, iNumberOfLines)
{

}

#define DISPLAY_VEHICLE_FLAG(X) DisplayFlagIfSet(m_Vehicle->m_nVehicleFlags.X, #X);

void CVehicleFlagDebugInfo::DisplayFlagIfSet(u8 bFlagValue, const char* szFlagName)
{
	if (bFlagValue)
	{
		ColorPrintLn(Color_green, "%s", ++szFlagName); //super safe, honest
	}
}

void CVehicleFlagDebugInfo::PrintRenderedSelection(bool bPrintAll)
{
	if(!m_Vehicle)
		return;

	if(!CVehicleIntelligence::m_bDisplayVehicleFlagsInfo && !bPrintAll)
		return;

	WriteLogEvent("VEHICLE FLAGS");
	PushIndent();
	PushIndent();
	PushIndent();

	//full list of displayed flags, copied from VehicleFlags.h
	//please keep these listed alphabetically
	DISPLAY_VEHICLE_FLAG(	bActAsIfHasSirenOn			)
	DISPLAY_VEHICLE_FLAG(	bActAsIfHighSpeedForFragSmashing )
	DISPLAY_VEHICLE_FLAG(	bActiveForPedNavigation		)
	DISPLAY_VEHICLE_FLAG(	bAICanUseExclusiveSeats		)
	DISPLAY_VEHICLE_FLAG(	bAlertWhenEntered			)
	DISPLAY_VEHICLE_FLAG(	bAllowBoundsToBeRaised		)
	DISPLAY_VEHICLE_FLAG(	uAllowedDummyConversion		)
	DISPLAY_VEHICLE_FLAG(	bAllowHomingMissleLockon	)
	DISPLAY_VEHICLE_FLAG(	bAllowKnockOffVehicleForLargeVertVel )
	DISPLAY_VEHICLE_FLAG(	bAllowNoPassengersLockOn	)
	DISPLAY_VEHICLE_FLAG(	bAnimateJoints				)
	DISPLAY_VEHICLE_FLAG(	bAnimatePropellers			)
	DISPLAY_VEHICLE_FLAG(	bAnimateWheels				)
	DISPLAY_VEHICLE_FLAG(	bApproachingJunctionWithSiren )
	DISPLAY_VEHICLE_FLAG(	bAreHydraulicsAllRaised		)
	DISPLAY_VEHICLE_FLAG(	bAudioBackfired				)
	DISPLAY_VEHICLE_FLAG(	bAudioBackfiredBanger		)
	DISPLAY_VEHICLE_FLAG(	bAutomaticallyAttaches		)
	DISPLAY_VEHICLE_FLAG(	bAvoidanceDirtyFlag			)
	DISPLAY_VEHICLE_FLAG(	bBecomeStationaryQuicker	)
	DISPLAY_VEHICLE_FLAG(	bBlipThrottleRandomly		)
	DISPLAY_VEHICLE_FLAG(	bBlownUp					)
	DISPLAY_VEHICLE_FLAG(	bBlowUpWhenMissingAllWheels )
	DISPLAY_VEHICLE_FLAG(	bCanBeDeletedWithAlivePedsInIt )
	DISPLAY_VEHICLE_FLAG(	bCanBeStolen				)
	DISPLAY_VEHICLE_FLAG(	bCanBeUsedByFleeingPeds		)
	DISPLAY_VEHICLE_FLAG(	bCanBeVisiblyDamaged		)
	DISPLAY_VEHICLE_FLAG(	bCanBreakOffWheelsWhenBlowUp)
	DISPLAY_VEHICLE_FLAG(	bCanDeformWheels			)
	DISPLAY_VEHICLE_FLAG(	bCanEngineDegrade				)
	DISPLAY_VEHICLE_FLAG(   bCanEngineMissFire			)
	DISPLAY_VEHICLE_FLAG(	bCanLeakOil					)
	DISPLAY_VEHICLE_FLAG(	bCanLeakPetrol				)
	DISPLAY_VEHICLE_FLAG(	bCanMakeIntoDummyVehicle	)
	DISPLAY_VEHICLE_FLAG(	bCannotRemoveFromWorld		)
	DISPLAY_VEHICLE_FLAG(	bCanPlayerAircraftEngineDegrade	)
	DISPLAY_VEHICLE_FLAG(	bCanPlayerCarLeakOil		)
	DISPLAY_VEHICLE_FLAG(	bCanPlayerCarLeakPetrol		)
	DISPLAY_VEHICLE_FLAG(	bCanSaveInGarage			)
	DISPLAY_VEHICLE_FLAG(	bCantTrafficJam				)
	DISPLAY_VEHICLE_FLAG(	bCarAgainstCarSideCollision	)
	DISPLAY_VEHICLE_FLAG(	bCarBrushAgainstCarSideCollision )
	DISPLAY_VEHICLE_FLAG(	bCarCrushingBike			)
	DISPLAY_VEHICLE_FLAG(	bCarHitByHeavyVehicle		)
	DISPLAY_VEHICLE_FLAG(	bCarHitBySuperHeavyVehicle	)
	DISPLAY_VEHICLE_FLAG(	bCarHitWhileInRoadBlock		)
	DISPLAY_VEHICLE_FLAG(	bCarNeedsToBeHotwired		)
	DISPLAY_VEHICLE_FLAG(	bCheckForMisalignmentOnDeactivation )
	DISPLAY_VEHICLE_FLAG(	bConsideredByPlayer			)
	DISPLAY_VEHICLE_FLAG(	bCountAsParkedCarForPopulation)
	DISPLAY_VEHICLE_FLAG(	bCountsTowardsAmbientPopulation )
	DISPLAY_VEHICLE_FLAG(	bCreatedByCarGen			)
	DISPLAY_VEHICLE_FLAG(	bCreatedByFactory			)
	DISPLAY_VEHICLE_FLAG(	bCreatedByLowPrioCargen		)
	DISPLAY_VEHICLE_FLAG(	bCreatedUsingCheat			)
	DISPLAY_VEHICLE_FLAG(	bCreatingAsInactive			)
	DISPLAY_VEHICLE_FLAG(	bDamageTrackingLocked       )
	DISPLAY_VEHICLE_FLAG(	bDisableAvoidanceProjection )
	DISPLAY_VEHICLE_FLAG(	bDisableEngineFires			)
	DISPLAY_VEHICLE_FLAG(   bDisableExplodeOnContact	)
	DISPLAY_VEHICLE_FLAG(	bDisableHeightMapAvoidance	)
	DISPLAY_VEHICLE_FLAG(	bDisableParticles			)
	DISPLAY_VEHICLE_FLAG(	bDisablePetrolTankDamage	)
	DISPLAY_VEHICLE_FLAG(	bDisablePetrolTankFires		)
	DISPLAY_VEHICLE_FLAG(	bDisablePretendOccupants	)
	DISPLAY_VEHICLE_FLAG(	bDisableRoadExtentsForAvoidance   )
	DISPLAY_VEHICLE_FLAG(	bDisableSuperDummy			)
	DISPLAY_VEHICLE_FLAG(	bDisableTowing				)
	DISPLAY_VEHICLE_FLAG(	bDisableVehicleMapCollision )
	DISPLAY_VEHICLE_FLAG(	bDisplayHighDetail			)
	DISPLAY_VEHICLE_FLAG(	bDoesProvideCover			)
	DISPLAY_VEHICLE_FLAG(	bDontSleepOnThisPhysical    )
	DISPLAY_VEHICLE_FLAG(	bDontStoreAsPersistent		)
	DISPLAY_VEHICLE_FLAG(	bDontTryToEnterThisVehicleIfLockedForPlayer )
	DISPLAY_VEHICLE_FLAG(	bDoorRatioHasChanged		)
	DISPLAY_VEHICLE_FLAG(	bDriveMusclesToAnim         )
	DISPLAY_VEHICLE_FLAG(	bDrivenDangerouslyExtreme	)
	DISPLAY_VEHICLE_FLAG(	bDrivenDangerouslyThisUpdate)
	DISPLAY_VEHICLE_FLAG(	bDrivingOnVehicle			)
	DISPLAY_VEHICLE_FLAG(	bDummyWheelImpactsSampled	)
	DISPLAY_VEHICLE_FLAG(	bEngineOn					)
	DISPLAY_VEHICLE_FLAG(	bEngineStarting				)
	DISPLAY_VEHICLE_FLAG(	bEngineWontStart			)
	DISPLAY_VEHICLE_FLAG(	bExplodesOnHighExplosionDamage )
	DISPLAY_VEHICLE_FLAG(   bExplodesOnNextImpact		)
	DISPLAY_VEHICLE_FLAG(	bFailedToResetPretendOccupants )
	DISPLAY_VEHICLE_FLAG(	bForceActiveDuringPlayback	)
	DISPLAY_VEHICLE_FLAG(	bForceAfterburnerVFX		)
	DISPLAY_VEHICLE_FLAG(	bForceBrakeLightOn			)
	DISPLAY_VEHICLE_FLAG(	bForceEnemyPedsFalloff		)
	DISPLAY_VEHICLE_FLAG(	bForceEngineDamageByBullet)
	DISPLAY_VEHICLE_FLAG(	bForceEntityScansAtHighSpeeds )
	DISPLAY_VEHICLE_FLAG(	bForceHd					)
	DISPLAY_VEHICLE_FLAG(	bForceInactiveDuringPlayback)
	DISPLAY_VEHICLE_FLAG(	bForceOtherVehiclesToOvertakeThisVehicle )
	DISPLAY_VEHICLE_FLAG(	bForceOtherVehiclesToStopForThisVehicle	)
	DISPLAY_VEHICLE_FLAG(	bForcePostCameraAiSecondaryTaskUpdate		)
	DISPLAY_VEHICLE_FLAG(	bForcePostCameraAnimUpdate	)
	DISPLAY_VEHICLE_FLAG(	bForcePostCameraAnimUpdateUseZeroTimeStep	)
	DISPLAY_VEHICLE_FLAG(	bFreebies					)
	DISPLAY_VEHICLE_FLAG(	bGangVeh					)
	DISPLAY_VEHICLE_FLAG(	bGeneratesEngineShockingEvents	)
	DISPLAY_VEHICLE_FLAG(	bHasBeenDriven				)
	DISPLAY_VEHICLE_FLAG(	bHasBeenOwnedByPlayer		)
	DISPLAY_VEHICLE_FLAG(	bHasBeenRepainted			)
	DISPLAY_VEHICLE_FLAG(	bHasBeenResprayed			)
	DISPLAY_VEHICLE_FLAG(	bHasBeenSeen				)
	DISPLAY_VEHICLE_FLAG(	bHasCoolingFan				)
	DISPLAY_VEHICLE_FLAG(	bHasDummyBound				)
	DISPLAY_VEHICLE_FLAG(	bHasDynamicNavMesh			)
#if ENABLE_FRAG_OPTIMIZATION
	DISPLAY_VEHICLE_FLAG(	bHasFragCacheEntry				)
#endif
	DISPLAY_VEHICLE_FLAG(	bHasGeneratedCover			)
	DISPLAY_VEHICLE_FLAG(	bHasGlowingBrakes			)
	DISPLAY_VEHICLE_FLAG(	bHasParentVehicle			)
	DISPLAY_VEHICLE_FLAG(	bHasProcessedAIThisFrame	)
	DISPLAY_VEHICLE_FLAG(	bHasSiren					)
	DISPLAY_VEHICLE_FLAG(	bHasWheelOnPavement			)
	DISPLAY_VEHICLE_FLAG(	bHazardLights				)
	DISPLAY_VEHICLE_FLAG(	bHeadlightsFullBeamOn		)
	DISPLAY_VEHICLE_FLAG(	bHideInCutscene				)
	DISPLAY_VEHICLE_FLAG(	bHornOnNetwork				)
	DISPLAY_VEHICLE_FLAG(	bIndicatorLights			)
	DISPLAY_VEHICLE_FLAG(	bInfluenceWantedLevel		)
	DISPLAY_VEHICLE_FLAG(	bInMotionFromExplosion		)
	DISPLAY_VEHICLE_FLAG(	bInSlownessZone				)
	DISPLAY_VEHICLE_FLAG(	bInteriorLightOn			)
	DISPLAY_VEHICLE_FLAG(	bIsAmbulanceOnDuty			)
	DISPLAY_VEHICLE_FLAG(	bIsAsleep					)
	DISPLAY_VEHICLE_FLAG(	bIsATargetPriority 			)
	DISPLAY_VEHICLE_FLAG(	bIsBeingTowed				)
	DISPLAY_VEHICLE_FLAG(	bIsBig						)
	DISPLAY_VEHICLE_FLAG(	bIsBus						)
	DISPLAY_VEHICLE_FLAG(	bIsCargoVehicle				)
	DISPLAY_VEHICLE_FLAG(	bIsCoolingFanOn				)
	DISPLAY_VEHICLE_FLAG(	bIsDeactivatedByPlayback	)
	DISPLAY_VEHICLE_FLAG(	bIsDoingHandBrakeTurn		)
	DISPLAY_VEHICLE_FLAG(	bIsDrowning					)
	DISPLAY_VEHICLE_FLAG(	bIsFarDrawEnabled			)
	DISPLAY_VEHICLE_FLAG(	bIsFireTruckOnDuty			)
	DISPLAY_VEHICLE_FLAG(	bIsHesitating				)
	DISPLAY_VEHICLE_FLAG(	bIsInCluster				)
	DISPLAY_VEHICLE_FLAG(	bIsInClusterBeingSpawned	)
	DISPLAY_VEHICLE_FLAG(	bIsInPopulationCache		)
	DISPLAY_VEHICLE_FLAG(	bIsInRecording				)
	DISPLAY_VEHICLE_FLAG(	bIsInRoadBlock				)
	DISPLAY_VEHICLE_FLAG(	bIsInTunnel					)
	DISPLAY_VEHICLE_FLAG(	bIsInVehicleReusePool		)
	DISPLAY_VEHICLE_FLAG(	bIsKERSBoostActive			)
	DISPLAY_VEHICLE_FLAG(	bIsLawEnforcementCar		)
	DISPLAY_VEHICLE_FLAG(	bIsLawEnforcementVehicle	)
	DISPLAY_VEHICLE_FLAG(	bIsNitrousBoostActive		)
	DISPLAY_VEHICLE_FLAG(	bIsOvertakingStationaryCar	)
	DISPLAY_VEHICLE_FLAG(	bIsParkedAtPetrolStation	)
	DISPLAY_VEHICLE_FLAG(	bIsParkedParallelly			)
	DISPLAY_VEHICLE_FLAG(	bIsParkedPerpendicularly	)
	DISPLAY_VEHICLE_FLAG(	bIsRacing					)
	DISPLAY_VEHICLE_FLAG(	bIsRacingConservatively		)
	DISPLAY_VEHICLE_FLAG(	bIsStolen					)
	DISPLAY_VEHICLE_FLAG(	bIsThisADriveableCar		)
	DISPLAY_VEHICLE_FLAG(	bIsThisAParkedCar			)
	DISPLAY_VEHICLE_FLAG(	bIsThisAStationaryCar		)
	DISPLAY_VEHICLE_FLAG(	bIsUnderMagnetControl		)
	DISPLAY_VEHICLE_FLAG(	bIsVan						)
	DISPLAY_VEHICLE_FLAG(	bIsWaitingToTurnLeft		)
	DISPLAY_VEHICLE_FLAG(	bKeepEngineOnWhenAbandoned	)
	DISPLAY_VEHICLE_FLAG(	bLeftIndicator				)
	DISPLAY_VEHICLE_FLAG(	bLerpToFullRecording		)
	DISPLAY_VEHICLE_FLAG(	bLightsAllowFullBeamSwitch	)
	DISPLAY_VEHICLE_FLAG(	bLightsButtonHeldDown		)
	DISPLAY_VEHICLE_FLAG(	bLightsOn					)
	DISPLAY_VEHICLE_FLAG(	bLimitSpeedWhenPlayerInactive)
	DISPLAY_VEHICLE_FLAG(	bLockDoorsOnCleanup			)
#if ENABLE_FRAG_OPTIMIZATION
	DISPLAY_VEHICLE_FLAG(	bLockFragCacheEntry				)
#endif
	DISPLAY_VEHICLE_FLAG(	bLodCanUseTimeslicing		)
	DISPLAY_VEHICLE_FLAG(	bLodCanUseTimeslicingAfterVisibilityChecks )
	DISPLAY_VEHICLE_FLAG(	bLodCanUseTimeslicingIfTooManyUpdates )
	DISPLAY_VEHICLE_FLAG(	bLodFarFromPopCenter		)
	DISPLAY_VEHICLE_FLAG(	bLodForceUpdateThisTimeslice)
	DISPLAY_VEHICLE_FLAG(	bLodForceUpdateUntilNextAiUpdate )
	DISPLAY_VEHICLE_FLAG(	bLodShouldSkipUpdatesInTimeslicedLod )
	DISPLAY_VEHICLE_FLAG(	bLodShouldUseTimeslicing	)
	DISPLAY_VEHICLE_FLAG(	bLodStrictRoadProximityTest	)
	DISPLAY_VEHICLE_FLAG(	bLodSuperDummyWheelCompressionSet	)
	DISPLAY_VEHICLE_FLAG(	bLowVehicle					)
	DISPLAY_VEHICLE_FLAG(	bMadDriver					)
	DISPLAY_VEHICLE_FLAG(	bMayBecomeParkedSuperDummy	)
	DISPLAY_VEHICLE_FLAG(	bMayHavePedDrivingDoorFlagSet )
	DISPLAY_VEHICLE_FLAG(	bMayHaveWheelGroundForcesToApply )
	DISPLAY_VEHICLE_FLAG(   bMercVeh					)
	DISPLAY_VEHICLE_FLAG(	bMissionVehToughAxles		)
	DISPLAY_VEHICLE_FLAG(	bMoreAccurateVirtualRoadProbes )
	DISPLAY_VEHICLE_FLAG(	bMoveAwayFromPlayer			)
	DISPLAY_VEHICLE_FLAG(	bNeverUseSmallerRemovalRange)
	DISPLAY_VEHICLE_FLAG(	bNoDummyPathAvailable		)
	DISPLAY_VEHICLE_FLAG(	bNonAmbientVehicleMayBeUsedByGoToPointAnyMeans )
	DISPLAY_VEHICLE_FLAG(	bNotDriveable				)
	DISPLAY_VEHICLE_FLAG(	bOtherCarsShouldCheckTrajectoryBeforeSpawning )
	DISPLAY_VEHICLE_FLAG(	bPartOfConvoy 				)
	DISPLAY_VEHICLE_FLAG(	bPartsBrokenOff				)
	DISPLAY_VEHICLE_FLAG(	bPetrolTankEmpty			)
	DISPLAY_VEHICLE_FLAG(	bPlaceOnRoadQueued			)
	DISPLAY_VEHICLE_FLAG(   bPlaneResistToExplosion		)
	DISPLAY_VEHICLE_FLAG(	bPlayerDrivingAgainstTraffic		)
	DISPLAY_VEHICLE_FLAG(	bPlayerHasTurnedOffLowBeamsAtNight )
	DISPLAY_VEHICLE_FLAG(	bPoliceFocusWillTrackCar	)
	DISPLAY_VEHICLE_FLAG(	bPreventBeingDummyThisFrame	)
	DISPLAY_VEHICLE_FLAG(	bPreventBeingDummyUnlessCollisionLoadedThisFrame )
	DISPLAY_VEHICLE_FLAG(	bPreventBeingSuperDummyThisFrame )
	DISPLAY_VEHICLE_FLAG(	bPreviousApproachingJunctionWithSiren )
	DISPLAY_VEHICLE_FLAG(	bProducingSlipStream		)
	DISPLAY_VEHICLE_FLAG( 	bRandomlyDelaySiren			)
	DISPLAY_VEHICLE_FLAG(	bReadyForCleanup			)
	DISPLAY_VEHICLE_FLAG(	bRearDoorsHaveBeenBlownOffByStickybomb	)
	DISPLAY_VEHICLE_FLAG(	bRefreshVisibility			)
	DISPLAY_VEHICLE_FLAG(	bRemoveWithEmptyCopOrWreckedVehs )
	DISPLAY_VEHICLE_FLAG(	bRepairWhenSafe				)
	DISPLAY_VEHICLE_FLAG(   bReportCrimeIfStandingOn	)
	DISPLAY_VEHICLE_FLAG(	bRequestDrawHD				)
	DISPLAY_VEHICLE_FLAG(	bRespectLocksWhenHasDriver  )
	DISPLAY_VEHICLE_FLAG(	bRestingOnPhysical 			)
	DISPLAY_VEHICLE_FLAG(	bRestorePlaybackVelAfterCollLoads )
	DISPLAY_VEHICLE_FLAG(	bRestoreVelAfterCollLoads	)
	DISPLAY_VEHICLE_FLAG(	bRightIndicator				)
	DISPLAY_VEHICLE_FLAG(	bRoofLowered				)
	DISPLAY_VEHICLE_FLAG(	bScansWithNonPlayerDriver	)
	DISPLAY_VEHICLE_FLAG(	bScheduledForCreation		)
	DISPLAY_VEHICLE_FLAG(	bScriptForceHd				)
	DISPLAY_VEHICLE_FLAG(	bScriptSetHandbrake			)
	DISPLAY_VEHICLE_FLAG(	bShouldBeBeepedAt			)
	DISPLAY_VEHICLE_FLAG(	bShouldBeRemovedByAmbientPed)
	DISPLAY_VEHICLE_FLAG(	bShouldFixIfNoCollision		)
	DISPLAY_VEHICLE_FLAG(	bShouldLerpFromAiToFullRecording	)
	DISPLAY_VEHICLE_FLAG(	bShouldNotChangeColour		)
	DISPLAY_VEHICLE_FLAG( 	bSiren						)
	DISPLAY_VEHICLE_FLAG(	bSirenUsesDayNightFade		)
	DISPLAY_VEHICLE_FLAG(	bSirenUsesEarlyFade			)
	DISPLAY_VEHICLE_FLAG(	bSirenUseNoLights			)
	DISPLAY_VEHICLE_FLAG(	bSirenUseNoSpec				)
	DISPLAY_VEHICLE_FLAG(	bSirenMutedByCode			)
	DISPLAY_VEHICLE_FLAG( 	bSirenMutedByScript			)
	DISPLAY_VEHICLE_FLAG(	bSkipEngineStartup			)
	DISPLAY_VEHICLE_FLAG(	bSlipStreamDisabledByTimeOut    )
	DISPLAY_VEHICLE_FLAG(	bSlowChillinDriver			)
	DISPLAY_VEHICLE_FLAG(	bStealable					)
	DISPLAY_VEHICLE_FLAG(	bStopInstantlyWhenPlayerInactive)
	DISPLAY_VEHICLE_FLAG(	bSuperDummyProcessed		)
	DISPLAY_VEHICLE_FLAG(	bSuppressBrakeLight			)
	DISPLAY_VEHICLE_FLAG(	bSwitchToAiRecordingThisFrame )
	DISPLAY_VEHICLE_FLAG(	bSyncPopTypeOnMigrate		)
	DISPLAY_VEHICLE_FLAG(	bTakeLessDamage				)
	DISPLAY_VEHICLE_FLAG(	bTargettableWithNoLos		)
	DISPLAY_VEHICLE_FLAG(	bTasksAllowDummying			)
	DISPLAY_VEHICLE_FLAG(	bTellOthersToHurry			)
	DISPLAY_VEHICLE_FLAG(	bToldToGetOutOfTheWay		)
	DISPLAY_VEHICLE_FLAG(	bTowedVehBoundsCanBeRaised	)
	DISPLAY_VEHICLE_FLAG(	bTryToRemoveAggressively	)
	DISPLAY_VEHICLE_FLAG(	bTurningLeftAtJunction		)
	DISPLAY_VEHICLE_FLAG(	bTyresDontBurst				)
	DISPLAY_VEHICLE_FLAG(	bUnbreakableLandingGear		)
	DISPLAY_VEHICLE_FLAG(	bUnbreakableLights			)
	DISPLAY_VEHICLE_FLAG(	bUnfreezeWhenCleaningUp		)
	DISPLAY_VEHICLE_FLAG(	bUpdateProducingSlipStream  )
	DISPLAY_VEHICLE_FLAG(	bUseAlternateHandling		)
	DISPLAY_VEHICLE_FLAG(	bUseCutsceneWheelCompression	)
	DISPLAY_VEHICLE_FLAG(	bUseDeformation				)
	DISPLAY_VEHICLE_FLAG(	bUsedForPilotSchool			)
	DISPLAY_VEHICLE_FLAG(	bUseScriptedCeilingHeight	)
	DISPLAY_VEHICLE_FLAG(	bUsesLargeRearRamp			)
	DISPLAY_VEHICLE_FLAG(	bUsingPretendOccupants		)
	DISPLAY_VEHICLE_FLAG(	bVehicleCanBeTargetted 		)
	DISPLAY_VEHICLE_FLAG(	bVehicleColProcessed 		)
	DISPLAY_VEHICLE_FLAG(	bVehicleInaccesible			)
	DISPLAY_VEHICLE_FLAG(	bVehicleIsOnscreen			)
	DISPLAY_VEHICLE_FLAG(	bWakeUpNextUpdate           )
	DISPLAY_VEHICLE_FLAG(	bWanted						)
	DISPLAY_VEHICLE_FLAG(	bWarnedPeds					)
	DISPLAY_VEHICLE_FLAG(	bWasCreatedByDispatch		)
	DISPLAY_VEHICLE_FLAG(	bWasOffroadWithConstraint	)
	BANK_ONLY(	DISPLAY_VEHICLE_FLAG(	bWasReused		))
	DISPLAY_VEHICLE_FLAG(	bWasStoppedForDoor			)
	DISPLAY_VEHICLE_FLAG(	bWheelsDisabled				)
	DISPLAY_VEHICLE_FLAG(	bWheelsDisabledOnDeactivation )
	DISPLAY_VEHICLE_FLAG(	bWheelsDontBreak			)
	DISPLAY_VEHICLE_FLAG(	bWheelShapetest				)
	DISPLAY_VEHICLE_FLAG(	bWillTurnLeftAgainstOncomingTraffic )
	DISPLAY_VEHICLE_FLAG(	bCheckForEnoughRoomToFitPed )
	
	PopIndent();
	PopIndent();
	PopIndent();
}

#endif