//DO NOT MODIFY THIS FILE!
//It was automatically generated by xlast2c v2.0


    
USING "commands_misc.sch"    
    
//PURPOSE
//   Enum with all achievements ids.
ENUM ACHIEVEMENT_ENUM
// REMEMBER THAT IN PS3 THERE IS ONE EXTRA ACHIEVEMENT
// #IF RSG_NP
//        PLATINUM = 0,
// #ENDIF //RSG_NP
        ACH00 = 1,
        ACH01 = 2,
        ACH02 = 3,
        ACH03 = 4,
        ACH04 = 5,
        ACH05 = 6,
        ACH06 = 7,
        ACH42 = 8,
        ACH07 = 9,
        ACH08 = 10,
        ACH09 = 11,
        ACH10 = 12,
        ACH11 = 13,
        ACH50 = 14,
        ACH12 = 15,
        ACH13 = 16,
        ACH14 = 17,
        ACH15 = 18,
        ACH16 = 19,
        ACH17 = 20,
        ACH18 = 21,
        ACH19 = 22,
        ACH20 = 23,
        ACH21 = 24,
        ACH22 = 25,
        ACH23 = 26,
        ACH24 = 27,
        ACH25 = 28,
        ACH26 = 29,
        ACH27 = 30,
        ACH28 = 31,
        ACH29 = 32,
        ACH30 = 33,
        ACH31 = 34,
        ACH32 = 35,
        ACH33 = 36,
        ACH34 = 37,
        ACH35 = 38,
        ACH36 = 39,
        ACH38 = 40,
        ACH39 = 41,
        ACH40 = 42,
        ACH41 = 43,
        ACH43 = 44,
        ACH45 = 45,
        ACH46 = 46,
        ACH47 = 47,
        ACH48 = 48,
        ACH49 = 49,
        ACH51 = 50,
        ACHH1 = 51,
        ACHH2 = 52,
        ACHH3 = 53,
        ACHH4 = 54,
        ACHH5 = 55,
        ACHH6 = 56,
        ACHH7 = 57,
        ACHH8 = 58,
        ACHH10 = 59,
        ACHH11 = 60,
        ACHR2 = 61,
        ACHR3 = 62,
        ACHR4 = 63,
        ACHR5 = 64,
        ACHR6 = 65,
        ACHR7 = 66,
        ACHR8 = 67,
        ACHR9 = 68,
        ACHR10 = 69,
        ACHGO1 = 70,
        ACHGO2 = 71,
        ACHGO3 = 72,
        ACHGO4 = 73,
        ACHGO5 = 74,
        ACHGO6 = 75,
        ACHGO7 = 76,
        ACHGO8 = 77,
    ACHIEVEMENT_COUNT = 78
ENDENUM
	//PURPOSE
	//   Returns the achievement enum given the name.
	FUNC ACHIEVEMENT_ENUM GET_ACHIEVEMENT_ENUM_BY_NAME_HASH(INT nameHash)
		IF GET_HASH_KEY("ACH00") = nameHash
			RETURN ACH00
		ELIF GET_HASH_KEY("ACH01") = nameHash
			RETURN ACH01
		ELIF GET_HASH_KEY("ACH02") = nameHash
			RETURN ACH02
		ELIF GET_HASH_KEY("ACH03") = nameHash
			RETURN ACH03
		ELIF GET_HASH_KEY("ACH04") = nameHash
			RETURN ACH04
		ELIF GET_HASH_KEY("ACH05") = nameHash
			RETURN ACH05
		ELIF GET_HASH_KEY("ACH06") = nameHash
			RETURN ACH06
		ELIF GET_HASH_KEY("ACH42") = nameHash
			RETURN ACH42
		ELIF GET_HASH_KEY("ACH07") = nameHash
			RETURN ACH07
		ELIF GET_HASH_KEY("ACH08") = nameHash
			RETURN ACH08
		ELIF GET_HASH_KEY("ACH09") = nameHash
			RETURN ACH09
		ELIF GET_HASH_KEY("ACH10") = nameHash
			RETURN ACH10
		ELIF GET_HASH_KEY("ACH11") = nameHash
			RETURN ACH11
		ELIF GET_HASH_KEY("ACH50") = nameHash
			RETURN ACH50
		ELIF GET_HASH_KEY("ACH12") = nameHash
			RETURN ACH12
		ELIF GET_HASH_KEY("ACH13") = nameHash
			RETURN ACH13
		ELIF GET_HASH_KEY("ACH14") = nameHash
			RETURN ACH14
		ELIF GET_HASH_KEY("ACH15") = nameHash
			RETURN ACH15
		ELIF GET_HASH_KEY("ACH16") = nameHash
			RETURN ACH16
		ELIF GET_HASH_KEY("ACH17") = nameHash
			RETURN ACH17
		ELIF GET_HASH_KEY("ACH18") = nameHash
			RETURN ACH18
		ELIF GET_HASH_KEY("ACH19") = nameHash
			RETURN ACH19
		ELIF GET_HASH_KEY("ACH20") = nameHash
			RETURN ACH20
		ELIF GET_HASH_KEY("ACH21") = nameHash
			RETURN ACH21
		ELIF GET_HASH_KEY("ACH22") = nameHash
			RETURN ACH22
		ELIF GET_HASH_KEY("ACH23") = nameHash
			RETURN ACH23
		ELIF GET_HASH_KEY("ACH24") = nameHash
			RETURN ACH24
		ELIF GET_HASH_KEY("ACH25") = nameHash
			RETURN ACH25
		ELIF GET_HASH_KEY("ACH26") = nameHash
			RETURN ACH26
		ELIF GET_HASH_KEY("ACH27") = nameHash
			RETURN ACH27
		ELIF GET_HASH_KEY("ACH28") = nameHash
			RETURN ACH28
		ELIF GET_HASH_KEY("ACH29") = nameHash
			RETURN ACH29
		ELIF GET_HASH_KEY("ACH30") = nameHash
			RETURN ACH30
		ELIF GET_HASH_KEY("ACH31") = nameHash
			RETURN ACH31
		ELIF GET_HASH_KEY("ACH32") = nameHash
			RETURN ACH32
		ELIF GET_HASH_KEY("ACH33") = nameHash
			RETURN ACH33
		ELIF GET_HASH_KEY("ACH34") = nameHash
			RETURN ACH34
		ELIF GET_HASH_KEY("ACH35") = nameHash
			RETURN ACH35
		ELIF GET_HASH_KEY("ACH36") = nameHash
			RETURN ACH36
		ELIF GET_HASH_KEY("ACH38") = nameHash
			RETURN ACH38
		ELIF GET_HASH_KEY("ACH39") = nameHash
			RETURN ACH39
		ELIF GET_HASH_KEY("ACH40") = nameHash
			RETURN ACH40
		ELIF GET_HASH_KEY("ACH41") = nameHash
			RETURN ACH41
		ELIF GET_HASH_KEY("ACH43") = nameHash
			RETURN ACH43
		ELIF GET_HASH_KEY("ACH45") = nameHash
			RETURN ACH45
		ELIF GET_HASH_KEY("ACH46") = nameHash
			RETURN ACH46
		ELIF GET_HASH_KEY("ACH47") = nameHash
			RETURN ACH47
		ELIF GET_HASH_KEY("ACH48") = nameHash
			RETURN ACH48
		ELIF GET_HASH_KEY("ACH49") = nameHash
			RETURN ACH49
		ELIF GET_HASH_KEY("ACH51") = nameHash
			RETURN ACH51
		ELIF GET_HASH_KEY("ACHH1") = nameHash
			RETURN ACHH1
		ELIF GET_HASH_KEY("ACHH2") = nameHash
			RETURN ACHH2
		ELIF GET_HASH_KEY("ACHH3") = nameHash
			RETURN ACHH3
		ELIF GET_HASH_KEY("ACHH4") = nameHash
			RETURN ACHH4
		ELIF GET_HASH_KEY("ACHH5") = nameHash
			RETURN ACHH5
		ELIF GET_HASH_KEY("ACHH6") = nameHash
			RETURN ACHH6
		ELIF GET_HASH_KEY("ACHH7") = nameHash
			RETURN ACHH7
		ELIF GET_HASH_KEY("ACHH8") = nameHash
			RETURN ACHH8
		ELIF GET_HASH_KEY("ACHH10") = nameHash
			RETURN ACHH10
		ELIF GET_HASH_KEY("ACHH11") = nameHash
			RETURN ACHH11
		ELIF GET_HASH_KEY("ACHR2") = nameHash
			RETURN ACHR2
		ELIF GET_HASH_KEY("ACHR3") = nameHash
			RETURN ACHR3
		ELIF GET_HASH_KEY("ACHR4") = nameHash
			RETURN ACHR4
		ELIF GET_HASH_KEY("ACHR5") = nameHash
			RETURN ACHR5
		ELIF GET_HASH_KEY("ACHR6") = nameHash
			RETURN ACHR6
		ELIF GET_HASH_KEY("ACHR7") = nameHash
			RETURN ACHR7
		ELIF GET_HASH_KEY("ACHR8") = nameHash
			RETURN ACHR8
		ELIF GET_HASH_KEY("ACHR9") = nameHash
			RETURN ACHR9
		ELIF GET_HASH_KEY("ACHR10") = nameHash
			RETURN ACHR10
		ELIF GET_HASH_KEY("ACHGO1") = nameHash
			RETURN ACHGO1
		ELIF GET_HASH_KEY("ACHGO2") = nameHash
			RETURN ACHGO2
		ELIF GET_HASH_KEY("ACHGO3") = nameHash
			RETURN ACHGO3
		ELIF GET_HASH_KEY("ACHGO4") = nameHash
			RETURN ACHGO4
		ELIF GET_HASH_KEY("ACHGO5") = nameHash
			RETURN ACHGO5
		ELIF GET_HASH_KEY("ACHGO6") = nameHash
			RETURN ACHGO6
		ELIF GET_HASH_KEY("ACHGO7") = nameHash
			RETURN ACHGO7
		ELIF GET_HASH_KEY("ACHGO8") = nameHash
			RETURN ACHGO8
		ENDIF
		RETURN ACHIEVEMENT_COUNT
	ENDFUNC
	//PURPOSE
	//   Hash the given string for getting the achievement.
	FUNC ACHIEVEMENT_ENUM GET_ACHIEVEMENT_ENUM_BY_NAME_STRING(STRING lbName)
		INT nameHash = GET_HASH_KEY(lbName)
		RETURN GET_ACHIEVEMENT_ENUM_BY_NAME_HASH(nameHash)
	ENDFUNC
