//DO NOT MODIFY THIS FILE!
//It was automatically generated by xlast2c v2.0


//PURPOSE
//   Enum with all gamemode ids.
ENUM GAMEMODE_ENUM
        GAMEMODE_0 = 0,
        GAMEMODE_4 = 4,
        GAMEMODE_3 = 3,
        GAMEMODE_1 = 1,
        GAMEMODE_6 = 6,
        GAMEMODE_5 = 5,
        GAMEMODE_2 = 2,
        GAMEMODE_COUNT = 7
ENDENUM
