////////////////////////////////////////////////////////////////////////////////
// WARNING: THIS FILE IS AUTOGENERATED. ANY CHANGES MADE WILL GET OVERWRITTEN //
////////////////////////////////////////////////////////////////////////////////

ENUM MATERIAL_NAMES
INVALID_MATERIAL=0,
TENNIS_FENCE_2=233925547,                                            // prop_fnclink_03a
GOLF_HARD_VEG3=581794674,                                            // bushes
TENNIS_FENCE_3=-2098049209,                                          // prop_fnclink_03b
GOLF_HARD_VEG4=-1915425863,                                          // tree_bark
GOLF_WATER_HAZARD=435688960,                                         // water
TENNIS_FENCE_4=450003561,                                            // prop_fnclink_03c
GOLF_MISC=-2073312001,                                               // plastic
GOLF_ROUGH2=930824497,                                               // grass_broken
GENERAL_SNOW_LOOSE=-1937569590,                                      // snow_loose
TENNIS_FENCE_5=1394765188,                                           // prop_fnclink_03d
TENNIS_TURF_2=-145735917,                                            // rubber
GOLF_FLAG_POLE=627123000,                                            // plastic_hollow
TRAIN_TRACKS_GRAVEL_2=2128369009,                                    // gravel_large
TENNIS_BLEACHERS_FLOOR=-365631240,                                   // metal_solid_medium
TENNIS_FENCE_6=125958708,                                            // metal_chainlink_large
TENNIS_FENCE=762193613,                                              // metal_chainlink_small
TENNIS_TURF_3=592446772,                                             // sandstone_solid
GOLF_SOFT_VEG=-2041329971,                                           // leaves
TRAIN_TRACKS_RAILS=-1447280105,                                      // metal_solid_small
TENNIS_BLEACHERS_SEATS_2=1849540536,                                 // metal_hollow_medium
TENNIS_TURF_4=669292054,                                             // carpet_solid
TENNIS_TURF=1907048430,                                              // paving_slab
GOLF_SAND=510490462,                                                 // sand_compact
GENERAL_SNOW_TARMAC=1550304810,                                      // snow_tarmac
GENERAL_SNOW_DEEP=1619704960,                                        // snow_deep
TENNIS_BLEACHERS_SEATS=-1625995479,                                  // plastic_high_density
TENNIS_TURF_5=1144315879,                                            // clay_hard
GOLF_PATH1=1187676648,                                               // concrete
TENNIS_NET=122789469,                                                // cloth
GOLF_DIRT_TRACK=-1885547121,                                         // dirt_track
GOLF_CART_PATH=951832588,                                            // gravel_small
GOLF_PATH2=282940568,                                                // tarmac
GOLF_FAIRWAY=1333033863,                                             // grass
GENERAL_SNOW_COMPACT=-878560889,                                     // snow_compact
TENNIS_INNER_WALLS=-642658848,                                       // tarpaulin
GOLF_FENCE_1=-1447280105,                                            // metal_solid_small
GOLF_GREEN=-1286696947,                                              // grass_short
TRAIN_TRACKS_GRAVEL=1925605558,                                      // gravel_train_track
GOLF_FENCE_2=762193613,                                              // metal_chainlink_small
GOLF_HARD_VEG1=-309121453,                                           // woodchips
GOLF_ROCKS=-840216541,                                               // rock
GOLF_HARD_VEG2=555004797,                                            // wood_solid_medium
GOLF_BUNKER=-1595148316,                                             // sand_loose
GOLF_ROUGH=-461750719                                                // grass_long
ENDENUM
