// script_hud_enums.sch
// all standard scaleform scripthud components


//
// eHUD_COMPONENT - list of all CODE hud components
//
ENUM eHUD_COMPONENT
	NEW_HUD_WANTED_STARS = 1,
	NEW_HUD_WEAPON_ICON,
	NEW_HUD_CASH,
	NEW_HUD_MP_CASH,
	NEW_HUD_MP_MESSAGE,
	NEW_HUD_VEHICLE_NAME,
	NEW_HUD_AREA_NAME,
	NEW_HUD_DISTRICT_NAME,	
	NEW_HUD_STREET_NAME,
	NEW_HUD_HELP_TEXT,
	NEW_HUD_FLOATING_HELP_TEXT_1,
	NEW_HUD_FLOATING_HELP_TEXT_2,
	NEW_HUD_CASH_CHANGE,			//	used to be NEW_HUD_FLOATING_HELP_TEXT_3
	NEW_HUD_RETICLE,
	NEW_HUD_SUBTITLE_TEXT,
	NEW_HUD_RADIO_STATIONS,
	NEW_HUD_SAVING_GAME,
	NEW_HUD_FEED,
	NEW_HUD_WEAPON_WHEEL,
	NEW_HUD_WEAPON_WHEEL_STATS
ENDENUM


//
// eSCRIPT_HUD_COMPONENT - list of all SCRIPT hud components
//
ENUM eSCRIPT_HUD_COMPONENT
	HUD_DRUGS_PURSE_01 = 0,
	HUD_DRUGS_PURSE_02,
	HUD_DRUGS_PURSE_03,
	HUD_DRUGS_PURSE_04,
	HUD_MP_TAG_CASH_FROM_BANK,
	HUD_MP_TAG_PACKAGES,
	HUD_MP_TAG_CUFF_KEYS,
	HUD_MP_TAG_DOWNLOAD_DATA,
	HUD_MP_TAG_IF_PED_FOLLOWING,
	HUD_MP_TAG_KEY_CARD,
	HUD_MP_TAG_RANDOM_OBJECT,
	HUD_MP_TAG_REMOTE_CONTROL,
	HUD_MP_TAG_CASH_FROM_SAFE,
	HUD_MP_TAG_WEAPONS_PACKAGE,
	HUD_MP_TAG_KEYS,
	HUD_MP_VEHICLE,
	HUD_MP_VEHICLE_HELI,
	HUD_MP_VEHICLE_PLANE,
	HUD_PLAYER_SWITCH_ALERT,
	HUD_MP_RANK_BAR,
	HUD_DIRECTOR_MODE

ENDENUM


//
// BRIEF_TYPE - types of brief string - for use with ADD_TEXT_COMPONENT_SUBSTRING_LATEST_BRIEF_STRING and SCALEFORM_MOVIE_METHOD_ADD_PARAM_LATEST_BRIEF_STRING
//
ENUM BRIEF_TYPE  // matches CMessages::ePreviousMessageTypes
	PREV_MESSAGE_TYPE_DIALOG = 0,
	PREV_MESSAGE_TYPE_HELP,
	PREV_MESSAGE_TYPE_MISSION
ENDENUM
