
// Keep all these different from one another to catch when too many of one type has been used   - maximum iterations follow in comments
CONST_INT MICRO_STACK_SIZE              	(128)  // 20
CONST_INT MINI_STACK_SIZE               	(512)  // 20
CONST_INT DEFAULT_STACK_SIZE            	(1424) // 68
CONST_INT SPECIAL_ABILITY_STACK_SIZE    	(1828) // 13
CONST_INT FRIEND_STACK_SIZE             	(2050) // 12
CONST_INT SHOP_STACK_SIZE               	(2324) // 6
CONST_INT CELLPHONE_STACK_SIZE          	(2552) // 2
CONST_INT VEHICLE_SPAWN_STACK_SIZE          (3568) // 1
CONST_INT CAR_MOD_SHOP_STACK_SIZE			(3600) // 2
CONST_INT PAUSE_MENU_SCRIPT_STACK_SIZE 		(3076) // 2
CONST_INT MULTIPLAYER_MISSION_STACK_SIZE	(5050) // 19
CONST_INT CONTACTS_APP_STACK_SIZE          	(4000) // 1
CONST_INT SMPL_INTERIOR_STACK_SIZE          (2512) // 1
CONST_INT WAREHOUSE_STACK_SIZE          	(14100) // 1 //also used for activity creator
CONST_INT IE_DELIVERY_STACK_SIZE			(2324) // 1
CONST_INT SHOP_CONTROLLER_STACK_SIZE        (3200) // 1

#IF IS_DEBUG_BUILD
CONST_INT DEBUG_SCRIPT_STACK_SIZE       	(4080) // 1
#ENDIF	//	IS_DEBUG_BUILD

//	CONST_INT SOAK_TEST_STACK_SIZE			(4088)	//	1		Only for code use. Do not use
//	CONST_INT NETWORK_BOT_STACK_SIZE		(4096)	//	31		Only for code use. Do not use

CONST_INT APP_INTERNET_STACK_SIZE           (4592) // 1

CONST_INT INTERACTION_MENU_STACK_SIZE		(9800) // 1

CONST_INT SCRIPT_XML_STACK_SIZE         	(8344) // 4
CONST_INT INGAMEHUD_STACK_SIZE				(4600) //1 //Brenda Needs this for the ingame hud. 
CONST_INT PROPERTY_INT_STACK_SIZE         	(19400) // 1		//4626
CONST_INT ACTIVITY_CREATOR_INT_STACK_SIZE   (15900) // 3
CONST_INT AM_MP_YACHT_STACK_SIZE         	(5000) // 3
CONST_INT TRANSITION_STACK_SIZE				(8032) //1
CONST_INT FMMC_LAUNCHER_STACK_SIZE			(24000) // 1
CONST_INT MULTIPLAYER_FREEMODE_STACK_SIZE	(70500) // 1 Mission Controller
CONST_INT MISSION_STACK_SIZE            	(53000) // 1 Mission Creator
CONST_INT MP_LAUNCH_SCRIPT_STACK_SIZE		(33750) // 1 <-- For freemode.sc

#IF IS_DEBUG_BUILD
CONST_INT DEBUG_MENU_STACK_SIZE				(35000) // 1
#ENDIF	//	IS_DEBUG_BUILD

