NATIVE CAMERA_INDEX
NATIVE CAMERA_ROUTE_INDEX
NATIVE GROUP_INDEX
NATIVE PLAYER_INDEX
NATIVE PARTICIPANT_INDEX
NATIVE PICKUP_INDEX
NATIVE PED_QUEUE_INDEX
NATIVE SEQUENCE_INDEX
NATIVE FIRE_INDEX
NATIVE MARKER_INDEX
NATIVE BLIP_INDEX
NATIVE RADAR_ZONE_MARK_INDEX
NATIVE MENU_INDEX
NATIVE INTERIOR_INSTANCE_INDEX
NATIVE SCHEDULE_INDEX
NATIVE NETWORK_INDEX
NATIVE VIEWPORT_INDEX
NATIVE DECISION_MAKER_INDEX
NATIVE VEHICLE_GENERATOR_INDEX
NATIVE PED_QUEUE_MEMBERSHIP_INDEX
NATIVE HOSPITAL_RESTART_INDEX
NATIVE POLICE_RESTART_INDEX
NATIVE SAVE_HOUSE_INDEX
NATIVE CHECKPOINT_INDEX
NATIVE RAYFIRE_INDEX
NATIVE SCALEFORM_INDEX
NATIVE SCALEFORM_CONTAINER_INDEX
NATIVE SCALEFORM_RETURN_INDEX
NATIVE INCIDENT_INDEX
NATIVE SAVED_INT_ID
NATIVE SAVED_FLOAT_ID
NATIVE SAVED_BOOL_ID
NATIVE SAVED_STRING_ID
NATIVE SHAPETEST_INDEX
NATIVE ROPE_INDEX
NATIVE RECORDING_ID
NATIVE STREAMVOL_ID
NATIVE SCENARIO_BLOCKING_INDEX
NATIVE VEHICLE_NODE_ID
NATIVE TIME_DATATYPE

NATIVE BINK_MOVIE_ID
NATIVE MOVIE_MESH_SET_ID
NATIVE GRASS_CULL_SPHERE_HANDLE

NATIVE DECAL_ID

NATIVE PEDHEADSHOT_ID

NATIVE VEHICLE_COMBAT_AVOIDANCE_AREA_INDEX

NATIVE ITEM_INDEX					// Corresponds to fwExtensibleBase in code.

NATIVE VOLUME : ITEM_INDEX
NATIVE ENTITY_INDEX : ITEM_INDEX

NATIVE VEHICLE_INDEX : ENTITY_INDEX
NATIVE PED_INDEX : ENTITY_INDEX
NATIVE OBJECT_INDEX : ENTITY_INDEX
NATIVE COVERPOINT_INDEX : ITEM_INDEX
NATIVE ITEMSET_INDEX : ITEM_INDEX
NATIVE PTFX_ID : ITEM_INDEX
NATIVE PLAYER_SCRIPT_ID : ITEM_INDEX

NATIVE HUDMARKER_ID
