#ifndef THREAD_PRIORITIES_H
#define THREAD_PRIORITIES_H

#include "system/ipc.h"

// main thread = PRIO_NORMAL
#define PRIO_AUDIO_THREAD					PRIO_HIGHEST
#define PRIO_RENDER_THREAD					PRIO_BELOW_NORMAL
#define PRIO_MOTION_TREE_THREAD				PRIO_BELOW_NORMAL
#define PRIO_PATHSERVER_THREAD				PRIO_NORMAL
#define PRIO_PTFX_THREAD					PRIO_ABOVE_NORMAL
#define PRIO_NETWORK_ASSET_VERIFIER_THREAD	PRIO_BELOW_NORMAL
#define PRIO_GETSAVENAMES_THREAD			PRIO_NORMAL
#define PRIO_SHAPETEST_DISPATCHER_THREAD	((rage::sysIpcPriority) (PRIO_LOWEST-1))
#define PRIO_SHAPETEST_ASYNC_THREAD			PRIO_ABOVE_NORMAL
#define PRIO_STREAMER_THREAD				PRIO_NORMAL
#define PRIO_SYSTEM_INFO_THREAD				PRIO_BELOW_NORMAL
#define PRIO_NETWORK_HASHER_UTIL_THREAD		PRIO_BELOW_NORMAL


#endif // THREAD_PRIORITIES_H
