#ifndef _INC_VISIBILITYMASKS_H_
#define _INC_VISIBILITYMASKS_H_

enum
{
	VIS_PHASE_OTHER					= 0,
	VIS_PHASE_GBUF,
	VIS_PHASE_CASCADE_SHADOWS,
	VIS_PHASE_PARABOLOID_SHADOWS,
	VIS_PHASE_PARABOLOID_REFLECTION,
	VIS_PHASE_WATER_REFLECTION,
	VIS_PHASE_MIRROR_REFLECTION,
	VIS_PHASE_RAIN_COLLISION_MAP,
	VIS_PHASE_SEETHROUGH_MAP,
	VIS_PHASE_STREAMING,

	VIS_PHASE_FLAG_SHADOW_PROXY,
	VIS_PHASE_FLAG_WATER_REFLECTION_PROXY,
	VIS_PHASE_FLAG_WATER_REFLECTION_PROXY_PRE_REFLECTED
};

enum
{
	VIS_ENTITY_OTHER				= 0,
	VIS_ENTITY_PED,
	VIS_ENTITY_OBJECT,
	VIS_ENTITY_DUMMY_OBJECT,
	VIS_ENTITY_VEHICLE,
	VIS_ENTITY_ANIMATED_BUILDING,
	VIS_ENTITY_LOLOD_BUILDING,
	VIS_ENTITY_HILOD_BUILDING,
	VIS_ENTITY_LIGHT,
	VIS_ENTITY_TREE,
	VIS_ENTITY_INSTANCELIST
};

enum
{
	VIS_PHASE_MASK_OTHER								= 1 << VIS_PHASE_OTHER,
	VIS_PHASE_MASK_GBUF									= 1 << VIS_PHASE_GBUF,
	VIS_PHASE_MASK_CASCADE_SHADOWS						= 1 << VIS_PHASE_CASCADE_SHADOWS,
	VIS_PHASE_MASK_PARABOLOID_SHADOWS					= 1 << VIS_PHASE_PARABOLOID_SHADOWS,
	VIS_PHASE_MASK_PARABOLOID_REFLECTION				= 1 << VIS_PHASE_PARABOLOID_REFLECTION,
	VIS_PHASE_MASK_WATER_REFLECTION						= 1 << VIS_PHASE_WATER_REFLECTION,
	VIS_PHASE_MASK_MIRROR_REFLECTION					= 1 << VIS_PHASE_MIRROR_REFLECTION,
	VIS_PHASE_MASK_RAIN_COLLISION_MAP					= 1 << VIS_PHASE_RAIN_COLLISION_MAP,
	VIS_PHASE_MASK_SEETHROUGH_MAP						= 1 << VIS_PHASE_SEETHROUGH_MAP,
	VIS_PHASE_MASK_STREAMING							= 1 << VIS_PHASE_STREAMING,

	VIS_PHASE_MASK_SHADOW_PROXY							= 1 << VIS_PHASE_FLAG_SHADOW_PROXY,
	VIS_PHASE_MASK_WATER_REFLECTION_PROXY				= 1 << VIS_PHASE_FLAG_WATER_REFLECTION_PROXY,
	VIS_PHASE_MASK_WATER_REFLECTION_PROXY_PRE_REFLECTED	= 1 << VIS_PHASE_FLAG_WATER_REFLECTION_PROXY_PRE_REFLECTED,

	VIS_PHASE_MASK_SHADOWS			=	VIS_PHASE_MASK_CASCADE_SHADOWS			|
										VIS_PHASE_MASK_PARABOLOID_SHADOWS,

	VIS_PHASE_MASK_REFLECTIONS		=	VIS_PHASE_MASK_PARABOLOID_REFLECTION	|
										VIS_PHASE_MASK_MIRROR_REFLECTION,

	VIS_PHASE_MASK_ALL				=	VIS_PHASE_MASK_OTHER					|
										VIS_PHASE_MASK_GBUF						|
										VIS_PHASE_MASK_CASCADE_SHADOWS			|
										VIS_PHASE_MASK_PARABOLOID_SHADOWS		|
										VIS_PHASE_MASK_PARABOLOID_REFLECTION	|
										VIS_PHASE_MASK_WATER_REFLECTION			|
										VIS_PHASE_MASK_MIRROR_REFLECTION		|
										VIS_PHASE_MASK_RAIN_COLLISION_MAP		|
										VIS_PHASE_MASK_SEETHROUGH_MAP			|
										VIS_PHASE_MASK_STREAMING
};

enum
{
	VIS_ENTITY_MASK_OTHER				= 1 << VIS_ENTITY_OTHER,
	VIS_ENTITY_MASK_PED					= 1 << VIS_ENTITY_PED,
	VIS_ENTITY_MASK_OBJECT				= 1 << VIS_ENTITY_OBJECT,
	VIS_ENTITY_MASK_DUMMY_OBJECT		= 1 << VIS_ENTITY_DUMMY_OBJECT,
	VIS_ENTITY_MASK_VEHICLE				= 1 << VIS_ENTITY_VEHICLE,
	VIS_ENTITY_MASK_ANIMATED_BUILDING	= 1 << VIS_ENTITY_ANIMATED_BUILDING,
	VIS_ENTITY_MASK_LOLOD_BUILDING		= 1 << VIS_ENTITY_LOLOD_BUILDING,
	VIS_ENTITY_MASK_HILOD_BUILDING		= 1 << VIS_ENTITY_HILOD_BUILDING,
	VIS_ENTITY_MASK_LIGHT				= 1 << VIS_ENTITY_LIGHT,
	VIS_ENTITY_MASK_TREE				= 1 << VIS_ENTITY_TREE,
	VIS_ENTITY_MASK_INSTANCELIST		= 1 << VIS_ENTITY_INSTANCELIST,

	VIS_ENTITY_MASK_ALL				=	VIS_ENTITY_MASK_OTHER				|
										VIS_ENTITY_MASK_PED					|
										VIS_ENTITY_MASK_OBJECT				|
										VIS_ENTITY_MASK_DUMMY_OBJECT		|
										VIS_ENTITY_MASK_VEHICLE				|
										VIS_ENTITY_MASK_ANIMATED_BUILDING	|
										VIS_ENTITY_MASK_LOLOD_BUILDING		|
										VIS_ENTITY_MASK_HILOD_BUILDING		|
										VIS_ENTITY_MASK_LIGHT				|
										VIS_ENTITY_MASK_TREE				|
										VIS_ENTITY_MASK_INSTANCELIST
};

#endif // !defined _INC_VISIBILITYMASKS_H_
