
#ifndef INC_ENTITYID_SHARED_H_
#define INC_ENTITYID_SHARED_H_

#define ENTITYSELECT_BIT_COUNT 64

#if ENTITYSELECT_BIT_COUNT == 32

#ifndef __SHADERMODEL
typedef u32 entitySelectID;
#define ENTITYSELECT_INVALID_ID 0xFFFFFFFFU
#endif //__SHADERMODEL

#define ENTITYSELECT_NO_OF_PLANES	1

#elif ENTITYSELECT_BIT_COUNT == 64

#ifndef __SHADERMODEL
typedef u64 entitySelectID;
#define ENTITYSELECT_INVALID_ID 0xFFFFFFFFFFFFFFFFU
#endif //__SHADERMODEL

#define ENTITYSELECT_NO_OF_PLANES	2

#endif // ENTITYSELECT_BIT_COUNT == 64

#endif // INC_ENTITYID_SHARED_H_

