//
// TaskMotionInTurretMoveNetworkMetadata.cpp
//
// Copyright (C) 1999-2013 Rockstar Games.  All Rights Reserved.
//
// FILE TO BE AUTO-GENERATED BY MAKENETWORK
//

////////////////////////////////////////////////////////////////////////////////

// File Header
#include "task\Motion\Vehicle\TaskMotionInTurretMoveNetworkMetadata.h"

// Game Headers
#include "task\Motion\Vehicle\TaskMotionInTurret.h"

////////////////////////////////////////////////////////////////////////////////

namespace TaskMotionInTurretMoveNetworkMetadata
{
	// Network
	const fwMvNetworkDefId                      NetworkId("TaskMotionInTurret", 0xed410f6c);

	// States
// 	const fwMvStateId                           StartId("Start", 0x84dc271f);
// 	const fwMvStateId                           ReverseId("Reverse", 0xae3930d7);
// 	const fwMvStateId                           RowTurnLowEffortId("RowTurnLowEffort", 0x8d03645b);
// 	const fwMvStateId                           RowLowEffortId("RowLowEffort", 0x9f922fe8);
// 	const fwMvStateId                           RowHighEffortId("RowHighEffort", 0xf17fef27);
// 	const fwMvStateId                           RowTurnHighEffortId("RowTurnHighEffort", 0x329f6aad);
// 
 	// Requests
 	const fwMvRequestId                         InvalidRequestId("Invalid", 0x8451f94f); // Invalid Request
	const fwMvRequestId                         AdjustStepRequestId("AdjustStep", 0xbb232703);
	const fwMvRequestId                         StreamAssetsRequestId("StreamAssets", 0x47953efe);
 	const fwMvRequestId                         IdleRequestId("Idle", 0x71c21326);
	const fwMvRequestId							TurningRequestId("Turning", 0x1943e429);
	const fwMvRequestId							ShuntRequestId("Shunt", 0x462ced36);

	// Flags
 	const fwMvFlagId                            FireFlagId("Fire", 0xd30a036b);
	const fwMvFlagId                            WobbleFlagId("Wobble", 0xd6cdf302);
	const fwMvFlagId                            WasTurningLeftFlagId("WasTurningLeft", 0xee6a2653);
	const fwMvFlagId                            Seated_LoopsFlagId("Seated_Loops", 0x7a4013da);
	const fwMvFlagId                            Seated_SweepsFlagId("Seated_Sweeps", 0x2783f80c);
	const fwMvFlagId                            Seated_SweepLoopsFlagId("Seated_SweepLoops", 0xD36A92CA);

 	// Events - On-Enter and On-Exit
 	const fwMvBooleanId                         Invalid_OnEnterId("Invalid", 0x8451f94f); // Invalid On-Enter Event
	const fwMvBooleanId                         AdjustStep_OnEnterId("AdjustStep_OnEnter", 0xada147ac);
	const fwMvBooleanId                         StreamAssets_OnEnterId("StreamAssets_OnEnter", 0xcbed51a5);
 	const fwMvBooleanId                         Idle_OnEnterId("Idle_OnEnter", 0xca902721);
	const fwMvBooleanId                         Turning_OnEnterId("Turning_OnEnter", 0x795f0a31);
	const fwMvBooleanId                         Shunt_OnEnterId("Shunt_OnEnter", 0x1b6094ca);

 	// Events - Other
 	const fwMvBooleanId                         BlendOut_AdjustStepId("BlendOut_AdjustStep", 0xb5766ee1);
	const fwMvBooleanId                         BlendOutShuntAnimId("BlendOutShuntAnim", 0x90ecaa24);	

	// Outputs
	const fwMvFloatId                           AdjustStep0PhaseId("AdjustStep0Phase", 0x36ac2790);
	const fwMvFloatId                           AdjustStep90PhaseId("AdjustStep90Phase", 0x337cb693);
	const fwMvFloatId                           AdjustStep180PhaseId("AdjustStep180Phase", 0x0398e6db);
 
 	// Parameters
	const fwMvClipId                            LowLodTurretClipId("LowLodTurretClip", 0xac823fb3);
 	const fwMvClipId                            Clip0Id("Clip0", 0xf416c5e4);
 	const fwMvClipId                            Clip1Id("Clip1", 0xd60c89c4);
 	const fwMvClipId                            Clip2Id("Clip2", 0xb58f45c);
 	const fwMvClipId                            Clip3Id("Clip3", 0xb193c0d3);
	const fwMvClipId                            Clip4Id("Clip4", 0xe6cd2b45);
	const fwMvClipId                            Clip5Id("Clip5", 0x951e87e9);
 	const fwMvFloatId                           PitchId("Pitch", 0x3f4bb8cc);
	const fwMvFloatId							HeadingId("Heading", 0x43f5cf44);
	const fwMvFloatId                           TurnSpeedId("TurnSpeed", 0xfd04f4d7);
	const fwMvFloatId                           InitialHeadingDeltaId("InitialHeadingDelta", 0x002e05f4);
	const fwMvFloatId                           RestartIdleBlendDurationId("RestartIdleBlendDuration", 0x20831b31);

	// Table which defines the ai-task state / anim-move network state coupling
// 	const TaskMoveNetworkStateInfo States[NUM_STATES] =
// 	{
// 		TaskMoveNetworkStateInfo(CTaskMotionRowingInCanoe::State_Start,             StartId,             Invalid_OnEnterId,          InvalidRequestId),
// 		TaskMoveNetworkStateInfo(CTaskMotionRowingInCanoe::State_Reverse,           ReverseId,           Reverse_OnEnterId,          ReverseRequestId),
// 		TaskMoveNetworkStateInfo(CTaskMotionRowingInCanoe::State_RowTurnLowEffort,  RowTurnLowEffortId,  RowTurnLowEffort_OnEnterId, RowTurnLowEffortRequestId),
// 		TaskMoveNetworkStateInfo(CTaskMotionRowingInCanoe::State_RowLowEffort,      RowLowEffortId,      RowLowEffort_OnEnterId,     RowLowEffortRequestId),
// 		TaskMoveNetworkStateInfo(CTaskMotionRowingInCanoe::State_RowHighEffort,     RowHighEffortId,     RowHighEffort_OnEnterId,    RowHighEffortRequestId),
// 		TaskMoveNetworkStateInfo(CTaskMotionRowingInCanoe::State_RowTurnHighEffort, RowTurnHighEffortId, RowHighEffort_OnEnterId,    RowTurnHighEffortRequestId),
// 	};
// 
// 	// Table defining all valid move network state transitions
// 	const MoveNetworkTransitionInfo Transitions[NUM_TRANSITIONS] =
// 	{
// 		MoveNetworkTransitionInfo(StartId,             RowLowEffortId),
// 		MoveNetworkTransitionInfo(StartId,             ReverseId),
// 		MoveNetworkTransitionInfo(StartId,             RowHighEffortId),
// 		MoveNetworkTransitionInfo(StartId,             RowTurnHighEffortId),
// 		MoveNetworkTransitionInfo(StartId,             RowTurnLowEffortId),
// 		MoveNetworkTransitionInfo(ReverseId,           RowHighEffortId),
// 		MoveNetworkTransitionInfo(ReverseId,           RowLowEffortId),
// 		MoveNetworkTransitionInfo(RowTurnLowEffortId,  RowLowEffortId),
// 		MoveNetworkTransitionInfo(RowTurnLowEffortId,  RowHighEffortId),
// 		MoveNetworkTransitionInfo(RowTurnLowEffortId,  RowTurnHighEffortId),
// 		MoveNetworkTransitionInfo(RowTurnLowEffortId,  ReverseId),
// 		MoveNetworkTransitionInfo(RowLowEffortId,      ReverseId),
// 		MoveNetworkTransitionInfo(RowLowEffortId,      RowTurnLowEffortId),
// 		MoveNetworkTransitionInfo(RowLowEffortId,      RowHighEffortId),
// 		MoveNetworkTransitionInfo(RowLowEffortId,      RowTurnHighEffortId),
// 		MoveNetworkTransitionInfo(RowHighEffortId,     RowTurnLowEffortId),
// 		MoveNetworkTransitionInfo(RowHighEffortId,     ReverseId),
// 		MoveNetworkTransitionInfo(RowHighEffortId,     RowLowEffortId),
// 		MoveNetworkTransitionInfo(RowHighEffortId,     RowTurnHighEffortId),
// 		MoveNetworkTransitionInfo(RowTurnHighEffortId, RowTurnLowEffortId),
// 		MoveNetworkTransitionInfo(RowTurnHighEffortId, RowLowEffortId),
// 		MoveNetworkTransitionInfo(RowTurnHighEffortId, RowHighEffortId),
// 		MoveNetworkTransitionInfo(RowTurnHighEffortId, ReverseId),
// 	};
}

////////////////////////////////////////////////////////////////////////////////