//
// TaskMotionInTurretMoveNetworkMetadata.h
//
// Copyright (C) 1999-2013 Rockstar Games.  All Rights Reserved.
//
// FILE TO BE AUTO-GENERATED BY MAKENETWORK
//

////////////////////////////////////////////////////////////////////////////////

#ifndef INC_TASKMOTIONINTURRET_MOVE_NETWORK_METADATA_H
#define INC_TASKMOTIONINTURRET_MOVE_NETWORK_METADATA_H

// Rage Headers
#include "fwanimation/animdefines.h"

// Game Headers
//#include "Task/System/TaskMoveNetworkHelpers.h"

////////////////////////////////////////////////////////////////////////////////

namespace TaskMotionInTurretMoveNetworkMetadata
{
	// Network
	extern const fwMvNetworkDefId               NetworkId;

	// States
// 	extern const fwMvStateId                    StartId;
// 	extern const fwMvStateId                    ReverseId;
// 	extern const fwMvStateId                    RowTurnLowEffortId;
// 	extern const fwMvStateId                    RowLowEffortId;
// 	extern const fwMvStateId                    RowHighEffortId;
// 	extern const fwMvStateId                    RowTurnHighEffortId;

	// Requests
	extern const fwMvRequestId                  InvalidRequestId; // Invalid Request
	extern const fwMvRequestId                  AdjustStepRequestId;
	extern const fwMvRequestId                  StreamAssetsRequestId;
	extern const fwMvRequestId                  IdleRequestId;
	extern const fwMvRequestId                  TurningRequestId;
	extern const fwMvRequestId                  ShuntRequestId;

	// Flags
	extern const fwMvFlagId                     FireFlagId;
	extern const fwMvFlagId                     WobbleFlagId;
	extern const fwMvFlagId                     WasTurningLeftFlagId;
	extern const fwMvFlagId						Seated_LoopsFlagId;
	extern const fwMvFlagId						Seated_SweepsFlagId;
	extern const fwMvFlagId						Seated_SweepLoopsFlagId;

	// Events - OnEnter and OnExit
	extern const fwMvBooleanId                  Invalid_OnEnterId; // Invalid On-Enter Event
	extern const fwMvBooleanId                  AdjustStep_OnEnterId;
	extern const fwMvBooleanId                  StreamAssets_OnEnterId;
	extern const fwMvBooleanId                  Idle_OnEnterId;
	extern const fwMvBooleanId					Turning_OnEnterId;
	extern const fwMvBooleanId					Shunt_OnEnterId;

	// Events - Other
	extern const fwMvBooleanId                  BlendOut_AdjustStepId;
	extern const fwMvBooleanId                  BlendOutShuntAnimId;

	// Outputs
 	extern const fwMvFloatId                    AdjustStep0PhaseId;
	extern const fwMvFloatId                    AdjustStep90PhaseId;
	extern const fwMvFloatId                    AdjustStep180PhaseId;

	// Parameters
	extern const fwMvClipId						LowLodTurretClipId;
 	extern const fwMvClipId                     Clip0Id;
 	extern const fwMvClipId                     Clip1Id;
 	extern const fwMvClipId                     Clip2Id;
 	extern const fwMvClipId                     Clip3Id;
	extern const fwMvClipId                     Clip4Id;
	extern const fwMvClipId                     Clip5Id;
 	extern const fwMvFloatId                    PitchId;
	extern const fwMvFloatId                    HeadingId;
	extern const fwMvFloatId					TurnSpeedId;
	extern const fwMvFloatId					InitialHeadingDeltaId;
	extern const fwMvFloatId					RestartIdleBlendDurationId;

	// Metadata used for transition validation
// 	const u32 NUM_STATES = 6;
// 	const u32 NUM_TRANSITIONS = 23;
// 
// 	// Array of valid move network transitions
// 	extern const MoveNetworkTransitionInfo      Transitions[NUM_TRANSITIONS];
// 	// Array of valid move network states
// 	extern const TaskMoveNetworkStateInfo       States[NUM_STATES];
}

////////////////////////////////////////////////////////////////////////////////

#endif // INC_TASKMOTIONROWINGINCANOE_MOVE_NETWORK_METADATA_H