
#include "fwrenderer/renderphaseswitches.h"

#define DRAW_LIST_MGR_SPLIT_GBUFFER				(((0 && RSG_PC) || (1 && RSG_ORBIS) || (1 && RSG_DURANGO)) && RENDER_PHASE_SUPPORT_MULIPLE_DRAW_LISTS)
#define DRAW_LIST_MGR_SPLIT_CASCADE_SHADOWS		(((1 && RSG_PC) || (1 && RSG_ORBIS) || (1 && RSG_DURANGO)) && RENDER_PHASE_SUPPORT_MULIPLE_DRAW_LISTS)
#define DRAW_LIST_MGR_SPLIT_PARABOLOID_SHADOWS	(((1 && RSG_PC) || (1 && RSG_ORBIS) || (1 && RSG_DURANGO)) && RENDER_PHASE_SUPPORT_MULIPLE_DRAW_LISTS)
#define DRAW_LIST_MGR_SPLIT_DRAWSCENE			(((1 && RSG_PC) || (1 && RSG_ORBIS) || (1 && RSG_DURANGO)) && RENDER_PHASE_SUPPORT_MULIPLE_DRAW_LISTS)


#if DRAW_LIST_MGR_SPLIT_GBUFFER
#define DRAW_LIST_MGR_SPLIT_GBUFFER_ONLY(x) x
#else
#define  DRAW_LIST_MGR_SPLIT_GBUFFER_ONLY(x)
#endif

#if DRAW_LIST_MGR_SPLIT_CASCADE_SHADOWS
#define DRAW_LIST_MGR_SPLIT_CASCADE_SHADOWS_ONLY(x) x
#else
#define  DRAW_LIST_MGR_SPLIT_CASCADE_SHADOWS_ONLY(x)
#endif

#if DRAW_LIST_MGR_SPLIT_PARABOLOID_SHADOWS
#define DRAW_LIST_MGR_SPLIT_PARABOLOID_SHADOWS_ONLY(x) x
#else
#define  DRAW_LIST_MGR_SPLIT_PARABOLOID_SHADOWS_ONLY(x)
#endif

#if DRAW_LIST_MGR_SPLIT_DRAWSCENE
#define DRAW_LIST_MGR_SPLIT_DRAWSCENE_ONLY(x) x
#define DRAW_LIST_MGR_SPLIT_DRAWSCENE_SWITCH(x,y) x
#else
#define  DRAW_LIST_MGR_SPLIT_DRAWSCENE_ONLY(x)
#define DRAW_LIST_MGR_SPLIT_DRAWSCENE_SWITCH(x,y) y
#endif
